sparkdesignsystem/spark-design-system

- packages/spark-core/package-lock.json
Reverts sparkdesignsystem/spark-design-system#106
> Revert "Update package v to resolve sec issue"

- README.md
- packages/spark-core/components/pagination.js
- packages/spark-core/package-lock.json
- packages/spark-core/spark-core.js
- packages/spark-core/tests/setAriaLabel.tests.js
- src/assets/drizzle/scripts/pagination/default.js
- src/assets/drizzle/scripts/pagination/long.js
- src/patterns/components/pagination/default.hbs
Added testing info to readme. Added set aria-label pagination tests. Broke up pagination.js to be able to import/export fns separately. Removed two unneeded css classes from .hbs pag file.
> Pagination tests

- package-lock.json
- package.json
- packages/spark-core/components/_icons.scss
- packages/spark-core/components/pagination.js
- packages/spark-core/components/toggle.js
- packages/spark-core/settings/_settings.scss
- packages/spark-core/spark-core.js
- packages/spark-core/tests/toggle.tests.js
- packages/spark-core/utilities/_utilities.scss
- src/assets/drizzle/scripts/drizzle.js
- src/assets/drizzle/scripts/pagination/default.js
- src/assets/drizzle/scripts/pagination/long.js
- src/pages/tests/icons.hbs
- src/pages/tests/toggle.hbs
- src/patterns/components/alerts/base.hbs
- src/patterns/components/icons/sizes.hbs
- src/patterns/components/toggle/base.hbs
- src/patterns/components/toggle/collection.yaml
- src/templates/blank.hbs
- src/templates/default.hbs
- add test page for toggle
- add icons and drizzle scripts to load on test pages(blank layout) and remove from regular layout to make sure they don't get loaded twice
- fix console errors for when there isn't a nav on page
- add toggle component (html,css,js)
- add new currentColor icon class
- add new icon class for flipped icon
- add toggle documentation
> Add Toggle Component

- packages/spark-core/components/toggle.js
- packages/spark-core/tests/toggle.tests.js
- src/patterns/components/accordions/base.hbs
> Accordion tests update

- src/assets/drizzle/scripts/navigation/mobileNav.js
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/189
> Add check for if mobilenav exists

- packages/spark-core/tests/setAriaLabel.tests.js
- src/assets/drizzle/scripts/pagination/default.js
- src/assets/drizzle/scripts/pagination/long.js
- tests/pagination.tests.js
- tests/setActiveNavItem.tests.js
So far, increase from 22 to 34.47%.
> Increase Spark Site Unit Test Coverage

- src/pages/gettingstarted/design-principles.hbs
Fixing the grammar a bit, then I thought our design adjective was setting a low goal so let's aim for greatness :)
> Why just be good?

- src/pages/gettingstarted/design-principles.hbs
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/276
> update inclusion per phil's comment on #276

- packages/spark-core/components/alerts.js
- packages/spark-core/spark-core.js
- packages/spark-core/tests/alerts.tests.js
- src/patterns/components/alerts/base.hbs
> Add JS for Alerts

- gulpfile.js
Documented issue with cssnano: https://github.com/ben-eb/gulp-cssnano/issues/8
https://github.com/sparkdesignsystem/spark-design-system/issues/403
> adding flag to prevent z-index minification

- package-lock.json
- packages/spark-core/_spark-core.scss
- packages/spark-core/base/_tables.scss
- src/assets/toolkit/styles/toolkit.scss
- src/pages/tests/example-two.hbs
- src/patterns/components/tables/column-comparison.hbs
- src/patterns/components/tables/grouped-columns.hbs
- src/patterns/components/tables/row-comparison.hbs
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/419
> Move tables from components to base

- src/patterns/components/card/collection.yaml
- src/patterns/components/card/three-up.hbs
- src/patterns/components/promo/collection.yaml
- src/patterns/components/toggle/collection.yaml
- src/patterns/fundamentals/layers/base.hbs
Change links to jump links and fix a couple of typos.
Fixes issue https://github.com/sparkdesignsystem/spark-design-system/issues/436
> Jump links

- src/templates/drizzle/item.hbs
Fixes issue https://github.com/sparkdesignsystem/spark-design-system/issues/444
> Component item metadata is not rendering

- src/angular/src/app/spark-core-angular/components/sprk-footer/sprk-footer.component.ts
- src/patterns/components/footer/angular/code/base-with-awards.hbs
- src/patterns/components/footer/angular/code/base.hbs
- src/patterns/components/footer/angular/code/optional-with-awards.hbs
- src/patterns/components/footer/angular/code/optional.hbs
- src/patterns/components/footer/angular/docs/base-with-awards.hbs
- src/patterns/components/footer/angular/docs/base.hbs
- src/patterns/components/footer/angular/docs/optional-with-awards.hbs
- src/patterns/components/footer/angular/docs/optional.hbs
- src/patterns/components/footer/angular/info/base-with-awards.hbs
- src/patterns/components/footer/angular/info/base.hbs
- src/patterns/components/footer/angular/info/optional.hbs
- src/patterns/components/footer/base-with-awards.hbs
- src/patterns/components/footer/base.hbs
- src/patterns/components/footer/collection.yaml
- src/patterns/components/footer/optional-with-awards.hbs
- src/patterns/components/footer/optional.hbs
This one was a complicated one. I feel we may need to revisit it after getting feedback from others.
> add angular docs for footer

- gulpfile.js
- packages/spark-core/settings/_settings.scss
- src/assets/drizzle/scripts/handlebars-helpers/concat.js
- src/assets/drizzle/scripts/handlebars-helpers/patternIdGen.js
- src/patterns/components/tables/collection.yaml
- src/patterns/components/tables/properties/collection.hbs
- src/templates/collection.hbs
- tests/patternIdGen.tests.js
small change to settings to override the table stripe color
Adding patternIdGen.js and concat.js in order to inject templates for Optional Properties into collection.hbs.
> Table stripes

- src/pages/docs/release-notes.hbs
Added release name with its github release tag link as list.
Closes #636
> Release notes page

- packages/spark-core/components/_alerts.scss
- src/angular/projects/spark-core-angular/src/lib/components/sprk-alert/sprk-alert.component.spec.ts
- src/angular/projects/spark-core-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
- src/patterns/components/alerts/angular/code/no-dismiss.hbs
- src/patterns/components/alerts/angular/info/info.hbs
- src/patterns/components/alerts/no-dismiss.hbs
> update alerts for not dismissible version + revamp ng

- packages/spark-core/base/_inputs.scss
- packages/spark-core/base/inputs/_labels.scss
- packages/spark-core/base/inputs/_text-input.scss
- src/angular/projects/spark-extras-angular-dictionary/src/lib/spark-extras-angular-dictionary.component.ts
- src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
- src/pages/tests/dictionary.hbs
- src/patterns/components/dictionary/base.hbs
- src/patterns/components/dictionary/striped.hbs
- src/patterns/components/inputs/angular/code/datepicker-disabled.hbs
- src/patterns/components/inputs/angular/code/datepicker-error.hbs
- src/patterns/components/inputs/angular/code/datepicker.hbs
- src/patterns/components/inputs/angular/code/monetary-disabled.hbs
- src/patterns/components/inputs/angular/code/monetary-error.hbs
- src/patterns/components/inputs/angular/code/monetary.hbs
- src/patterns/components/inputs/datepicker.hbs
- src/patterns/components/inputs/monetary.hbs
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/693
Create a component for a text input with icon
Inline Inputs
Date inputs
Currently, the structuring and css is not correct. There are containers with only modifier classes. There are modifier classes that modify components incorrectly
> Refactor input HTML and CSS into BEM implementation

- package-lock.json
- packages/spark-core/_spark-core.scss
- packages/spark-core/package-lock.json
- packages/spark-extras/components/card/package-lock.json
- packages/spark-extras/components/dictionary/package-lock.json
- packages/spark-extras/package-lock.json
- src/angular/package-lock.json
- src/assets/toolkit/styles/toolkit.scss
Removing references to Scales side-by-side object
> Side by side erasure

- src/data/colors.yaml
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/783
> BUG Fix: Gray color value in docs

- packages/spark-core/components/_buttons.scss
- packages/spark-core/settings/_settings.scss
- packages/spark-extras/components/card/_card.scss
- src/patterns/components/tables/secondary-row-comparison.hbs
> update secondary btn hover styles + card border style + table sec. row btns

- packages/spark-core/components/_buttons.scss
- packages/spark-core/settings/_settings.scss
- src/angular/src/app/spark-docs/button-docs/button-docs.component.ts
- src/patterns/components/buttons/at-small.hbs
- src/patterns/components/buttons/at-xsmall.hbs
- src/patterns/components/buttons/collection.yaml
- src/patterns/components/buttons/secondary-disabled.hbs
- src/patterns/components/buttons/submission.hbs
- src/patterns/components/buttons/tertiary-disabled.hbs
Updating all styles for buttons. We are moving away from red as our primary color.
Issue https://github.com/sparkdesignsystem/spark-design-system/issues/916
> Button refactor

- packages/spark-core/base/_links.scss
- packages/spark-core/settings/_settings.scss
- src/angular/projects/spark-core-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
- src/patterns/components/awards/primary.hbs
- src/patterns/components/card/base.hbs
- src/patterns/components/footer/footer.hbs
- src/patterns/components/links/collection.yaml
- src/patterns/components/links/inline.hbs
* Removed muted link styles and associated variables
* Changed "Inline Link" to "Base Link" in the docs
* Updated the class modifier table in Links docs to describe what each class does
* Updated Cards docs to use `.sprk-b-Link--has-icon`
* Update Award docs to use `.sprk-b-Link--has-icon`
* Update Footer docs to use `.sprk-b-Link--has-icon`
> Links misc

- src/angular/projects/spark-core-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
- src/angular/src/app/spark-docs/dropdown-docs/dropdown-docs.component.ts
- src/angular/src/app/spark-docs/masthead-docs/masthead-docs.component.ts
- src/patterns/components/dropdown/angular/info/base.hbs
Add two new inputs to dropdown component
> Update Angular Dropdown component

- src/pages/docs/release-notes.hbs
- src/patterns/fundamentals/layers/base.hbs
Brings the release notes page up to date and fixes outdated layers doc page. Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1033
> Update Release Notes

- src/patterns/components/buttons/base.hbs
- src/patterns/components/buttons/collection.yaml
- src/patterns/components/buttons/tertiary.hbs
Updates button documentation with content strategy's suggestions for https://github.com/sparkdesignsystem/spark-design-system/issues/1004.
> #1004 - Update Button docs

- src/pages/tests/example-two.hbs
Updates the example-two page to use the new footer so it's not out of date. Fixes: https://github.com/sparkdesignsystem/spark-design-system/issues/997
> #997 - Update example two test page

- src/angular/src/app/spark-docs/stack-docs/stack-docs.component.ts
- src/pages/tests/example-two.hbs
- src/patterns/fundamentals/grid/angular/code/stack-object-thirty-seventy-cols.hbs
- src/patterns/fundamentals/grid/stack-object-thirty-seventy-cols.hbs
Adds angular example code for the 30/70 layout to Spark docs.
> Update angular stack 30/70 docs

- src/react/src/routes/NotFound/NotFound.js
- src/react/src/routes/Router.js
Adds a 404 page to the React app.
> add 404 page for react app

- src/patterns/components/alerts/fail.hbs
- src/patterns/components/alerts/info.hbs
- src/patterns/components/alerts/no-dismiss.hbs
- src/patterns/components/alerts/react/code/base.hbs
- src/patterns/components/alerts/react/code/fail.hbs
- src/patterns/components/alerts/react/code/info.hbs
- src/patterns/components/alerts/react/code/no-dismiss.hbs
- src/patterns/components/alerts/react/code/success.hbs
- src/patterns/components/alerts/react/info/fail.hbs
- src/patterns/components/alerts/react/info/info.hbs
- src/patterns/components/alerts/react/info/success.hbs
- src/patterns/components/alerts/success.hbs
- src/react/projects/spark-core-react/src/SprkAlert/SprkAlert.js
- src/react/projects/spark-core-react/src/SprkAlert/SprkAlert.test.js
- src/react/projects/spark-core-react/src/index.js
- src/react/src/components/SiteNav/SiteNav.js
- src/react/src/routes/Router.js
- src/react/src/routes/SprkAlertDocs/SprkAlertDocs.js
- src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Adds the react alert component.
> Add React alert

- src/react/projects/spark-core-react/src/SprkAlert/SprkAlert.test.js
quick hotfix for failing alerts test
> fix failing alert test

- package-lock.json
- src/patterns/components/dictionary/base.hbs
- src/patterns/components/dictionary/react/code/base.hbs
- src/patterns/components/dictionary/react/code/striped.hbs
- src/patterns/components/dictionary/react/docs/base.hbs
- src/patterns/components/dictionary/react/info/base.hbs
- src/patterns/components/dictionary/react/info/striped.hbs
- src/patterns/components/dictionary/striped.hbs
- src/react/projects/spark-core-react/src/SprkDictionary/SprkDictionary.js
- src/react/projects/spark-core-react/src/SprkDictionary/SprkDictionary.test.js
- src/react/projects/spark-core-react/src/index.js
- src/react/src/components/SiteNav/SiteNav.js
- src/react/src/routes/Router.js
- src/react/src/routes/SprkDictionaryDocs/SprkDictionaryDocs.js
> React Dictionary component

- .github/pull_request_template.md
Added Associated Issue Area to the PR Template
> Added Associated Issue

- src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
- src/patterns/components/inputs/angular/code/datepicker-disabled.hbs
- src/patterns/components/inputs/angular/code/datepicker-error.hbs
- src/patterns/components/inputs/angular/code/datepicker.hbs
- src/patterns/components/inputs/angular/code/inline-search-input.hbs
- src/patterns/components/inputs/angular/code/monetary-disabled.hbs
- src/patterns/components/inputs/angular/code/monetary-error.hbs
- src/patterns/components/inputs/angular/code/monetary.hbs
Fixes a documentation mistake for angular datepicker component
> update datepicker example for angular

- .eslintrc
- package-lock.json
- package.json
- src/react/projects/spark-core-react/src/SprkFooter/SprkFooter.js
Adds prettier plugin to eslint config, adjust max-len rule
Removes unnecessary eslint run in lint-staged
* On Save, should set up editors to run prettier-eslint --write on changed files (if you want to)
> setting up prettier eslint config, adjusting eslint rc

- src/patterns/components/dictionary/react/code/base.hbs
- src/patterns/components/dictionary/react/code/striped.hbs
- src/patterns/components/dictionary/react/docs/base.hbs
- src/patterns/components/dictionary/react/info/base.hbs
- src/react/projects/spark-core-react/src/SprkDictionary/SprkDictionary.js
- src/react/projects/spark-core-react/src/SprkDictionary/SprkDictionary.test.js
- src/react/src/routes/SprkDictionaryDocs/SprkDictionaryDocs.js
Updates react dictionary to linting standards and adds React keys.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1053
> React Dictionary

- src/patterns/components/awards/primary.hbs
- src/patterns/components/awards/react/code/primary.hbs
- src/patterns/components/awards/react/info/primary.hbs
- src/react/projects/spark-core-react/src/SprkAward/SprkAward.js
- src/react/projects/spark-core-react/src/SprkAward/SprkAward.test.js
- src/react/projects/spark-core-react/src/SprkFooter/SprkFooter.js
- src/react/projects/spark-core-react/src/SprkFooter/SprkFooter.test.js
- src/react/projects/spark-core-react/src/SprkFooter/components/SprkFooterAwards/SprkFooterAwards.js
- src/react/projects/spark-core-react/src/SprkFooter/components/SprkFooterConnectIcons/SprkFooterConnectIcons.js
- src/react/projects/spark-core-react/src/SprkFooter/components/SprkFooterGlobalSection/SprkFooterGlobalSection.js
- src/react/projects/spark-core-react/src/SprkFooter/components/SprkFooterGlobalSection/SprkFooterGlobalSection.test.js
- src/react/projects/spark-core-react/src/SprkStack/components/SprkStackItem/SprkStackItem.js
- src/react/projects/spark-core-react/src/index.js
- src/react/src/components/SiteNav/SiteNav.js
- src/react/src/routes/Router.js
- src/react/src/routes/SprkAwardDocs/SprkAwardDocs.js
- src/react/src/routes/SprkFooterDocs/SprkFooterDocs.js
Adds the React Award Component, documentation and tests. The Award component uses the SprkStack component so this PR has a dependency on the SprkStack PR.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1068
> Add React Award

- src/patterns/components/inputs/angular/code/select.hbs
Updates the Angular Select code on the inputs page to match our Angular docs Select input and include the sprk-icon.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1105.
> Fix bug #1105

- src/patterns/components/alerts/angular/code/no-dismiss.hbs
Fixes docs bug for Angular Alerts .
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1153
> Fix bug #1153

- src/angular/projects/spark-core-angular/package.json
- src/angular/projects/spark-extras-angular-award/package.json
- src/angular/projects/spark-extras-angular-card/package.json
- src/angular/projects/spark-extras-angular-dictionary/package.json
- src/angular/projects/spark-extras-angular-highlight-board/package.json
> update package versions

- src/angular/projects/spark-core-angular/package.json
- src/angular/projects/spark-extras-angular-award/package.json
- src/angular/projects/spark-extras-angular-card/package.json
- src/angular/projects/spark-extras-angular-dictionary/package.json
- src/angular/projects/spark-extras-angular-highlight-board/package.json
Updates Spark Angular packages.
> Publish 3/21/19

- packages/spark-card/package.json
- packages/spark-core/package-lock.json
- packages/spark-core/package.json
- packages/spark-dictionary/package.json
- packages/spark-highlight-board/package-lock.json
- packages/spark-highlight-board/package.json
moves the testing stuff into dev deps
> updating versions

- .travis.yml
- packages/spark-core/package-lock.json
- packages/spark-core/package.json
- packages/spark-highlight-board/package-lock.json
- packages/spark-highlight-board/package.json
moving test stuff to dev dependencies
> updating dependencies

- src/pages/gettingstarted/react.hbs
Updates the getting started documentation for React to clarify react-core and spark extras.
#1245
> Update React Getting Started Docs

- .eslintrc
- src/react/projects/spark-react/src/SprkAccordion/SprkAccordion.js
Get rid of default props on accordion, and turn off es lint rule that requires default props on non-required props.
https://github.com/sparkdesignsystem/spark-design-system/issues/1203
> Accordion changes and improvements

- src/patterns/components/buttons/react/info/base.hbs
Adds analyticsString to the documentation for the SprkButton component.
#1246 
> Fix bug #1246

- src/pages/docs/release-notes.hbs
Updates the release notes page.
> updated release notes

- src/patterns/components/buttons/react/info/base.hbs
- src/react/projects/spark-react/src/SprkButton/SprkButton.js
- src/react/projects/spark-react/src/SprkButton/SprkButton.test.js
- src/react/src/routes/SprkButtonDocs/SprkButtonDocs.js
Refactor SprkButton in React to render an anchor tag if a href is provided.
Fixes #1252 
> Fix Bug-1252

- src/patterns/components/links/react/code/icon-text.hbs
- src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Removes an old TODO comment.
Fixes #1323
> remove old todo

- _redirects
- src/pages/docs/release-notes.hbs
Updates release notes page and adds a redirect for the developers page that is removed.
> release notes update

- src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
- src/angular/src/app/spark-docs/masthead-extended-docs/masthead-extended-docs.component.ts
- src/patterns/components/masthead/angular/code/extended.hbs
- src/patterns/components/masthead/angular/info/default.hbs
Fixes a bug with hardcoded dropdown link
> fixing go elsewhere bug

- packages/spark-core/spark-core-exports.js
- src/angular/src/styles.scss
Cleans up an old ref in the exports file.
> Remove import to function that was removed 

- src/angular/projects/spark-core-angular/package-lock.json
- src/angular/projects/spark-core-angular/package.json
> version bump for bug fixes

- packages/spark-core/package-lock.json
- packages/spark-core/package.json
- packages/spark-core/spark-core-exports.js
- src/angular/projects/spark-core-angular/package.json
Bug fix publish! Also, adds in code that is already in staging to remove func from exports file that causes a build warning.
> 5/3/19 - 🦟  Publish 10.1.1 bug fix patch to Core

- packages/spark-core/tests/stepper.tests.js
- src/patterns/components/stepper/stepper--dark-bg.hbs
Issue Number that this PR is closing out.
expected.
> change ids to id for stepper three desc

- packages/spark/package-lock.json
- packages/spark/package.json
- src/angular/projects/spark-angular/package.json
- src/react/projects/spark-react/package-lock.json
- src/react/projects/spark-react/package.json
Updates the version numbers from publishing.
> version updates from publish

- react/.babelrc
- react/.storybook/config.js
- react/.storybook/webpack.config.js
- react/package-lock.json
- react/package.json
Gets storybook to build, but hardcoded accordion story
> Mono split

- src/patterns/components/stepper/collection.yaml
- src/templates/collection.hbs
Add coming soon text for angular, turn off for react
Fixes #1466
> Add coming soon text for angular, turn off for react

- src/angular/src/app/spark-docs/icon-set-docs/icon-set-docs.component.ts
- src/angular/src/app/spark-docs/masthead-extended-docs/masthead-extended-docs.component.ts
- src/data/icons.yaml
- src/patterns/components/masthead/angular/code/extended.hbs
- src/patterns/components/masthead/extended.hbs
- src/patterns/components/masthead/react/code/extended.hbs
- src/react/src/routes/SprkMastheadExtendedDocs/SprkMastheadExtendedDocs.js
Updates the user icon in the masthead documentation.
Fixes #1458
> Update masthead icon

- packages/spark/components/_stepper.scss
Fixes number 6 on https://github.com/sparkdesignsystem/spark-design-system/issues/1481.
Number 6 on https://github.com/sparkdesignsystem/spark-design-system/issues/1481.
OLD:
NEW:
> fix heading color on stepper w/dark bg

- src/patterns/components/masthead/collection.yaml
Update masthead documentation for scroll event on narrow viewports for Vanilla.
> update masthead docs

- src/assets/toolkit/styles/toolkit.scss
- src/patterns/components/masthead/collection.yaml
> Update Doc site

- src/react/projects/spark-react/package-lock.json
- src/react/projects/spark-react/package.json
> update jest for security alerts around handlebars and yaml

- src/assets/drizzle/styles/base/_inputs.scss
- src/assets/drizzle/styles/main.scss
- src/assets/drizzle/styles/objects/_main-layout.scss
- src/assets/drizzle/styles/vendor/_algolia.scss
- src/templates/default.hbs
- src/templates/drizzle/nav.hbs
Sets up algolia search on the docs site.
#1438 
> set up algolia search

- src/react/projects/spark-react/src/SprkStepper/SprkStepper.js
- src/react/projects/spark-react/src/SprkStepper/SprkStepper.test.js
- src/react/projects/spark-react/src/SprkStepper/components/SprkStepperSlider/SprkStepperSlider.test.js
- src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.js
- src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.test.js
Add more unit tests to React Stepper
Issue https://github.com/sparkdesignsystem/spark-design-system/issues/1534
> React Stepper - more unit tests

- .github/pull_request_template.md
Adds manual testing plan checklist to PR template.
fixes #1596 
[x] update code template file
[x] no browser testing needed with this task
> Add manual testing plan checklist to PR template

- .travis.yml
- packages/spark/components/_stepper.scss
- packages/spark/settings/_settings.scss
- src/patterns/components/stepper/collection.yaml
- src/react/projects/spark-react/src/SprkStepper/SprkStepper.js
- src/react/projects/spark-react/src/SprkStepper/components/SprkStepperSlider/SprkStepperSlider.js
Add CSS animation for React Stepper
https://github.com/sparkdesignsystem/spark-design-system/issues/1535
> React Stepper slider animations

- .travis.yml
- packages/spark/components/masthead.js
- packages/spark/package-lock.json
- packages/spark/package.json
> added lodash to deps, adjusted import in masthead

- src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.js
- src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.test.js
- src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkInputIconCheck.js
- src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkInputLabel.js
- src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkLabelLocationCheck.js
- src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkTextareaCheck.js
- src/react/src/routes/SprkInputDocs/SprkTextInputDocs/SprkTextInputDocs.js
React version of huge text input
Fixes #1502
> Huge input react

- src/assets/drizzle/styles/components/_navigation.scss
- src/assets/drizzle/styles/objects/_main-layout.scss
- src/templates/default.hbs
- src/templates/drizzle/nav.hbs
Fixes a bug with the scrolling of the nav by repositioning the search field.
> moves the search into the nav header

- .github/pull_request_template.md
Issue Number that this PR is closing out.
expected.
> add fixes to pr tpl

- src/angular/projects/spark-angular/src/lib/components/inputs/sprk-huge-input-container/sprk-huge-input-container.component.spec.ts
- src/angular/projects/spark-angular/src/lib/components/inputs/sprk-huge-input-container/sprk-huge-input-container.component.ts
- src/angular/projects/spark-angular/src/lib/components/inputs/sprk-huge-input-container/sprk-huge-input-container.module.ts
- src/angular/projects/spark-angular/src/lib/components/inputs/sprk-input-container/sprk-input-container.component.ts
- src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts
- src/angular/projects/spark-angular/src/lib/spark-angular.module.ts
- src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
- src/patterns/components/inputs/angular/code/text-input-huge-disabled.hbs
- src/patterns/components/inputs/angular/code/text-input-huge-error.hbs
- src/patterns/components/inputs/angular/code/text-input-huge.hbs
Creates a floating label effect for the Huge Text Inputs for Angular.
Fixes #1501
> Angular Floating Label - Huge Input

- packages/spark/package-lock.json
- packages/spark/package.json
> updated version

- package-lock.json
- packages/spark/utilities/_utilities.scss
- src/angular/package-lock.json
- src/angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle-animations.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
- src/angular/projects/spark-angular/src/public_api.ts
- src/patterns/utilities/multi-property/typography.hbs
Fix toggle/accordion animations bug in newer Angular versions. Add a new utility to remove the TextCrop we apply on type and document it on the utilities page.
Fixes #1683 
> fix angular toggle/accordion animations in newer versions

- src/angular/projects/spark-angular/src/lib/components/sprk-list-item/sprk-list-item.component.spec.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-list-item/sprk-list-item.component.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-ordered-list.component.spec.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-ordered-list.component.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.spec.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.module.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.spec.ts
- src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.ts
> IE 11 - ordered lists not numbering - list refactor

- src/patterns/components/lists/angular/code/list.hbs
Update closing tag in lists angular code example.
> update list docs code example

- .stylelintrc
- packages/spark/components/_accordions.scss
- packages/spark/settings/_settings.scss
- src/patterns/components/accordions/collection.yaml
Adds style interaction for accordions
Fixes #1700
> Accordion hover style bug

- src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-datepicker/sprk-datepicker.directive.ts
Fixes the select event handler for datepicker to test for IE11 event dispatch support.
Fixes #1681
> updated datepicker directive to account for IE11 event issue

- packages/spark/components/masthead.js
- packages/spark/package-lock.json
- packages/spark/package.json
Merges in the changes that we had in master that were not in staging to the staging branch.
no issue
- no docs needed
- no code written, just branching strategy
- nothing needed here
- nothing needed here
- nothing needed here
- nothing needed here
- nothing needed here
> Update Staging with Master's changes

- packages/spark/package.json
- src/angular/projects/spark-angular/package.json
- src/react/projects/spark-react/package.json
Updates the version numbers of the Spark packages.
Fixes #1716 
-- Browser testing is not needed for this
-- Design Review is not needed for this
> Ready release version numbers

- src/angular/projects/spark-angular/ng-package.json
- src/angular/projects/spark-angular/package-lock.json
- src/angular/projects/spark-angular/package.json
- src/react/package-lock.json
- src/react/package.json
- src/react/projects/spark-react/package-lock.json
- src/react/projects/spark-react/package.json
Update the dependency version for the react site, react components, and angular components. The Angular PeerDependency has been changed to a Dependency.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1719.
> Bump lodash version to 4.17.15

- src/assets/drizzle/styles/utility/_toolkit-overrides.scss
- src/assets/toolkit/styles/toolkit.scss
Fixes the masthead scrolling on the test pages.
-- No issue for this.
-- No documentation updates.
-- Not applicable for this PR.
-- No design review needed.
expected.
> Masthead Scroll Doc Fix

- src/react/package.json
Update react dev app peerDeps to new spark versions.
No issue made.
> Update react dev app peerDeps to new spark versions

- src/angular/src/app/spark-docs/pagination-docs/pagination-docs.component.ts
Clean up test code on Angular Pagination test page. Also added a test case that uses the component in a realistic context.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1725
> Add use case to Angular Pagination test page

- packages/spark/settings/_settings.scss
- src/patterns/components/inputs/collection.yaml
- src/patterns/fundamentals/typography/body-one.hbs
- src/patterns/fundamentals/typography/body-three.hbs
- src/patterns/fundamentals/typography/body-two.hbs
Updates the body font sizes to match new design standard.
Fixes #1729 
> updated font sizing

- packages/spark/base/inputs/_svg-icon-input.scss
- packages/spark/base/inputs/_text-icon-input.scss
- packages/spark/base/inputs/_text-input.scss
- src/patterns/components/inputs/percentage.hbs
Updates to Bob's PR for percent-input-vanilla
> Vanilla Percent Input Updates

- packages/spark/base/inputs/_svg-icon-input.scss
- packages/spark/base/inputs/_text-input.scss
- packages/spark/settings/_settings.scss
- src/patterns/components/inputs/collection.yaml
Update class table and variable names for the Vanilla Percent Input
> Percent Vanilla Updates

- packages/spark/base/inputs/_svg-icon-input.scss
- src/angular/projects/spark-angular/src/lib/components/inputs/sprk-icon-input-container/sprk-icon-input-container.component.ts
- src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
- src/patterns/components/inputs/angular/code/percentage-disabled.hbs
- src/patterns/components/inputs/angular/code/percentage-error.hbs
- src/patterns/components/inputs/angular/code/percentage.hbs
- src/patterns/components/inputs/percentage-disabled.hbs
- src/patterns/components/inputs/percentage-error.hbs
- src/patterns/components/inputs/percentage.hbs
Angular version of percentage input
Fixes #1640 
-- no changes needed
> Angular percentage input

- gulp/angular/spark-angular/spark-angular.gulpfile.js
- packages/spark/package-lock.json
- packages/spark/package.json
- packages/spark/spark.js
- packages/spark/utilities/versionCheck.js
- packages/spark/webpack.config.js
- src/angular/projects/spark-angular/ng-package.json
- src/angular/projects/spark-angular/package-lock.json
- src/angular/projects/spark-angular/package.json
- src/angular/projects/spark-angular/src/environment/environment.ts
- src/angular/projects/spark-angular/src/lib/spark-angular.module.ts
- src/react/package-lock.json
- src/react/projects/spark-react/package-lock.json
- src/react/projects/spark-react/package.json
- src/react/projects/spark-react/src/Utilities/VersionCheck/VersionCheck.js
- src/react/projects/spark-react/src/index.js
- src/react/projects/spark-react/webpack.config.js
Brings in master's changes into staging
> Staging update

- src/angular/projects/spark-angular/package-lock.json
- src/angular/projects/spark-angular/package.json
- src/angular/projects/spark-angular/src/environment/environment.ts
Bumps the spark angular version so we can publish a new version of spark angular.
no issue yet
> publish hotfix

- spark/components/dropdown/react/SprkDropdown.stories.js
Adds React Dropdown to Storybook
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1878
> Adds React Dropdown to Storybook

- spark/components/pagination/react/SprkPagination.stories.js
- spark/components/pagination/react/SprkPagination.test.js
Add React Pagination to Storybook
Fixes #1884
> Add React Pagination to Storybook

- spark/components/masthead/react/SprkMasthead.js
- spark/components/masthead/react/SprkMasthead.stories.js
- spark/components/masthead/react/SprkMasthead.test.js
- spark/components/modals/react/SprkModal.js
- spark/components/stepper/react/SprkStepper.test.js
- spark/components/stepper/react/components/SprkStepperStep/SprkStepperStep.test.js
- spark/manifests/spark-react/package-lock.json
- spark/manifests/spark-react/package.json
- spark/utilities/testing/react/windowStubs.js
removes usage of spark vanilla js from spark-react, adds windowStubs, masthead tweaks
> Remove vanilla js usage from spark-react

- packages/spark/package-lock.json
- packages/spark/package.json
- src/angular/projects/spark-angular/package-lock.json
- src/angular/projects/spark-angular/package.json
- src/angular/projects/spark-angular/src/environment/environment.ts
- src/react/projects/spark-react/package-lock.json
- src/react/projects/spark-react/package.json
Update pkg versions to new beta version.
No issue, but we are creating new beta versions so that we can publish a new version of spark-angular to get out the most recent fix to the masthead for testing.
- nothing needed here
- nothing needed here
- nothing needed here, we'll test as a team with the new beta
- nothing needed here
- nothing needed here
> update pkg versions to new beta version

- src/data/icons.yaml
$ and % icons should be filled
> Fill those icons

- packages/spark/package.json
- src/angular/projects/spark-angular/package.json
- src/react/projects/spark-react/package.json
Adds in the correct versions to be published..
A part of the release effort.
- none
- update versions
- none
- none needed but everything loads fine in chrome after bump
- none needed
- none needed
> ready spark versions for publish

- packages/spark/spark-exports.js
- src/angular/projects/spark-angular/package-lock.json
- src/data/icons.yaml
- src/patterns/components/inputs/react/global-info.hbs
- src/react/projects/spark-react/package-lock.json
Tiny clean ups to publish (typos ETC)
no issue
> Tiny clean ups to publish (typos ETC)

- src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
removes vanilla js usage from angular masthead
> removes vanilla js usage from angular masthead

- spark/base/tables/vanilla/tables.stories.js
Add stories for the tables component for Vanilla Storybook.
Fixes #1819
> Tables - Vanilla

- spark/components/alerts/vanilla/alerts.stories.js
Set up stories and initial renders for vanilla Alert components
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1793
> Storybook vanilla alert

- spark/components/icons/react/SprkIcon.stories.js
Adds a story for each icon in React.
Fixes #1880
> Icon Stories for React

- angular/.storybook/config.js
- angular/.storybook/webpack.config.js
- angular/package-lock.json
- spark/components/alerts/angular/sprk-alert.stories.ts
- spark/components/buttons/angular/sprk-button.stories.ts
Adds examples for the team for how to write ng stories. Adds wrapper div for ng stories.
fixes #2154 
> adds method for writing ng stories (component or directive

- spark/components/footer/react/SprkFooter.js
- spark/components/footer/vanilla/footer.stories.js
> Add footer default story

- spark/components/accordions/vanilla/accordions.stories.js
Updates the Accordion story for vanilla.
Fixes #1791
> Update accordion story for vanilla

- spark/base/inputs/styles/_select.scss
- spark/base/inputs/vanilla/datePicker.js
- spark/base/inputs/vanilla/inputs.stories.js
- spark/objects/horizontal-list/styles/_horizontal-list.scss
Adds in the input stories in a new file called inputs.stories.js.
Fixes #1805 
> Add Input stories to SB html

- spark/components/modals/react/SprkModal.stories.js
- spark/components/modals/vanilla/modals.stories.js
- vanilla/.storybook/config.js
Adds three variants of modal for the Vanilla Storybook site
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1809
> Storybook vanilla modal

- spark/base/links/vanilla/links.stories.js
Link Stories for vanilla
Fixes #1807
> Add different link stories

- storybook-spark-theme.js
I need to keep that file there for the other sb deploys until their structure PRs get merged
> Put the sb theme file back in the root

- spark/components/card/vanilla/card.stories.js
Adds card stories to SB vanilla.
Fixes #1825 
> Add cards to html SB

- angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
Adds stories to Angular Storybook for Divider and Dropdown
Fixes #1840 
Fixes #1842 
Divider
Dropdown
Divider
Dropdown
Divider
Dropdown
Divider
Dropdown
> Add Angular components - Divider, Dropdown

- angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
Adds icon stories for Angular Storybook.
Fixes #1846
> Add Icons to Angular Storybook

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
Removes unnecessary input from examples.
Fixes #1842
> remove choiceMade input from examples

- angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
Adds toggle component story to angular storybook.
Fixes #1866 
> add toggle component story to angular storybook

- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
Adds stories to angular storybook - Footer, Table, Links
Fixes #1844 
Fixes #1862 
Fixes #1850 
Footer
Tables
Links
Footer
Tables
Links
Footer
Tables
Links
Footer
Tables
Links
> Angular Components Storybook

- angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
Adds Tabbed Navigation and Award stories for Angular
Fixes #1864 
Fixes #1874 
Tabbed Navigation
Award
Tabbed Navigation
Award
Tabbed Navigation
Award
Tabbed Navigation
Award
> Angular - Tabbed Navigation & Award

- html/.storybook/config.js
- html/base/inputs.stories.js
- html/base/links.stories.js
- html/base/tables.stories.js
- html/components/accordions.stories.js
- html/components/alerts.stories.js
- html/components/awards.stories.js
- html/components/button.stories.js
- html/components/card.stories.js
- html/components/dictionary.stories.js
- html/components/dividers.stories.js
- html/components/dropdown.stories.js
- html/components/footer.stories.js
- html/components/highlight-board.stories.js
- html/components/icons.stories.js
- html/components/masthead.stories.js
- html/components/modals.stories.js
- html/components/pagination.stories.js
- html/components/promo.stories.js
- html/components/stepper.stories.js
- html/components/tabs.stories.js
- html/components/toggle.stories.js
The container that surrounds each component is set globally, some components need individual changes, this allows for it.
Fixes #2185 
No changes on component side.
> Vanilla - Add the decorator individually for every component

- angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-list.stories.ts
- html/base/list.stories.js
Adds the List component stories for HTML & Angular
Fixes #2268 
Fixes #2266 
expected.
> Add list component to SB - HTML & Angular

- storybook-theming/_docs.scss
use source for settings for docs style overrides
quick fix
> use source for settings for docs style overrides

- react/src/components/footer/SprkFooter.stories.js
- react/src/components/masthead/SprkMasthead.stories.js
Fix duplicate exports on masthead and footer from bad merge
> masthead and footer had duplicate exports

- html/.storybook/config.js
- html/components/centered-column.stories.js
- storybook-theming/_docs.scss
Add centered column to HTML sb and add CSS for placeholder.
Fixes #2340 
> add centered column to HTML sb

- html/components/stack.stories.js
- storybook-theming/_docs.scss
Adds the stack object to the list of components for the HTML storybook.
Fixes #2343 
> add Stack to html sb

- angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts
Adds Stack component to Storybook for Angular.
Fixes #2316
> add stack stories for angular storybook

- html/components/_accordions.scss
- html/components/_alerts.scss
Adds comments to the scss for class modifiers for Accordion and Alert.
Fixes #2413
> add scss comments for accordion && alert

- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
> Bump angular to alpha

- react/package-lock.json
- react/package.json
> Bump react to alpha

- html/package-lock.json
- html/package.json
> Bump html to alpha

- html/components/divider.stories.js
- react/src/components/dividers/SprkDivider.stories.js
> remove hr divider stories in react and html

- angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
> update buttons to button in angular primary

- html/components/tabs.stories.js
Fix tabs in HTML storybook.
Fixes #2438
> add sprk-u-JavaScript to tabs decorator

- src/pages/index.hbs
add drizzle alert banner about new docs site.
don't have one
> add drizzle alert banner about new docs site

- html/components/button.stories.js
Adds a story for the HTML button to show it as a link element.
Fixes #2398
> add 'as link element' story for html button

- src/pages/using-spark/components/divider.mdx
Adds the divider docs to the gatsby site.
Fixes #2275
> Add Divider docs to NDS

- src/pages/using-spark/components/dictionary.mdx
Adds Dictionary documentation to Gatsby site.
Fixes #2285
> Add Dictionary docs to NDS

- src/pages/using-spark/components/box.mdx
add box content  to gatsby.
Fixes #2322 
> add box content to gatsby

- angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
- html/base/inputs/DatePicker.stories.js
- react/src/base/inputs/DatePicker.stories.js
update datepicker story to resolve datepicker already declared error
> update datepicker story to resolve datepicker already declared error

- src/pages/using-spark/components/award.mdx
Add award page doc content.
Fixe #2283 
> add award page doc content

- src/pages/using-spark/components/card.mdx
> add card content to gatsby

- angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
- react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
- react/src/components/highlight-board/SprkHighlightBoard.js
- react/src/components/promo/SprkPromo.js
- src/pages/using-spark/components/card.mdx
- src/pages/using-spark/components/promo.mdx
Adds Promo documentation to the Gatsby site.
Fixes #2290
> Promo docs for NDS

- html/objects/flag.stories.js
- react/src/components/modals/SprkModal.stories.js
Update HTML flag img to be smaller by using an icon instead so that it stacks nicely in iframe.
Fixes #2517
> Update HTML flag img to be smaller by using an icon instead so that it stacks nicely in iframe

- angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
Updates the angular links in stories
Fixes #2551 
> update angular links

- gatsby-config.js
Fixes typo to resolve principles nav bug.
Fixes #2593
> fix typo to fix principles nav bug

- html/components/stepper.stories.js
Fixes JS and CSS issues in Stepper (HTML).
Fixes iFrame issue on Gatsby site. 
Fixes #2446
> Stepper Updates

- package-lock.json
- package.json
> remove unneeded pkg

- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
- react/src/components/dictionary/SprkDictionary.js
Updates pkg jsons and removes unneeded defaultProps from SprkDictionary react component. It was causing an error in tests.
Fixes #2671 
> pkg json updates

- html/base/inputs/dateInput.js
- html/base/inputs/datePicker.js
- html/base/inputs/hugeInput.js
- html/base/inputs/monetaryInput.js
- html/base/inputs/passwordInput.js
- html/base/inputs/phoneInput.js
- html/base/inputs/requiredSelect.js
- html/base/inputs/requiredTextInput.js
- html/base/inputs/requiredTick.js
- html/base/inputs/ssnInput.js
- html/spark-exports.js
- html/spark.js
- html/tests/dateInput.tests.js
- html/tests/datePicker.tests.js
- html/tests/hugeInput.tests.js
- html/tests/monetaryInput.tests.js
- html/tests/phoneInput.tests.js
- html/tests/requiredTextInput.tests.js
- html/tests/requiredTick.tests.js
- html/tests/ssnInput.tests.js
Moves the input js files into the inputs directory and updates import file paths.
Fixes #2670
> Input JS file updates

- src/pages/using-spark/components/list.mdx
Adds List docs to Gatsby.
Fixes (#2649 
> add list docs to gatsby

- src/pages/principles/accessibility-guidelines.mdx
> add a11y guidelines to nds

- src/pages/docs/accessibility.hbs
Adds in guidelines to a11y page.
no PR, special request
- update a11y page
> add guidelines special request

- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- react/package.json
updates beta publish versions.
no issue for this
- update pkg jsons
> beta publish versions

- html/base/inputs/DatePicker.stories.js
- html/base/inputs/HugeSelect.stories.js
- html/base/inputs/HugeText.stories.js
> update file paths

- src/pages/using-spark/components/stack.mdx
Adds in the content we created for Stack to the gatsby site.
Fixes #2701 
> Add Stack Docs to NDS

- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
- html/components/footer.stories.js
- react/src/components/footer/SprkFooter.stories.js
- storybook-utilities/getStorybookInstance.js
Updates the footer stories for HTML, React and Angular to include the correct sister company logos and descriptions. 
Updates the getStorybookInstance utility to work on netlify deploy previews.
Fixes #2690
> Update Footer stories with sister company logos

- src/pages/installing-spark.mdx
- src/pages/using-spark.mdx
Updates the content for the Installing and Using landing pages.
Clean-up
> Updated the content for the installing and using landing pages

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/.npmignore
- html/package-lock.json
- html/package.json
- package-lock.json
- package.json
- react/.npmignore
- react/package-lock.json
- react/package.json
Update version numbers in packages.
Fixes #2679 
> version bumps for publish

- angular/projects/spark-angular/src/lib/components/inputs/Password.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
- html/base/inputs/Password.stories.js
- html/components/alert.stories.js
- react/src/components/alerts/SprkAlert.stories.js
- src/pages/using-spark/components/alert.mdx
- src/pages/using-spark/components/button.mdx
- src/pages/using-spark/components/dropdown.mdx
- src/pages/using-spark/components/highlight-board.mdx
- src/scss/_spark-theme.scss
Updates styles for the code elements.
Move accessibility docs for Alert.
Remove extra accessibility bullet for Button.
Add minHeight to Dropdown previews.
Add link to background image/text contrast ratio resource on Highlight Board.
Update Password docs for HTML & Angular.
> New Doc Site Clean Up

- react/src/spark-exports-react.js
> add export for SprkStepper

- src/pages/using-spark/components/input.mdx
- src/scss/_spark-theme.scss
Add jump links to inputs docs page.
> add list of variants and jump links for inputs

- src/components/Header.js
The components are listed in the mobile nav twice, this fixes it
> Remove repeating subnav items

- src/pages/installing-spark/angular.mdx
- src/pages/installing-spark/html-add-components.mdx
- src/pages/installing-spark/html-environment-setup.mdx
- src/pages/installing-spark/html-installation.mdx
- src/pages/installing-spark/installing-icons.mdx
- src/pages/installing-spark/react.mdx
> Nds cleanup katie

- src/pages/using-spark/foundations/space.mdx
> NDS Cleanup - Katie

- src/pages/installing-spark/html-add-components.mdx
> Smoke test fixes

- src/pages/installing-spark/html-installation.mdx
> Fix mixed inline code+text link

- angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts
Updates failing unit test for sprk-card in Angular.
> update failing test

- react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js
- react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
Change htmlFor attribute on input to id
Fixes #2195
> change htmlFor to id on input

- src/pages/principles/design-principles.mdx
Updating the language in our design patterns
Fixes #2811 
> Update design principles

- src/pages/installing-spark/html-environment-setup.mdx
Switch steps 13 and 14 in the HTML Environment Setup Guide.
[Current Page](https://sparkdesignsystem.com/installing-spark/html-environment-setup/)
[Updated Page](https://deploy-preview-2827--spark-design-system.netlify.com/installing-spark/html-environment-setup) 
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2826
> Update to HTML Environment Setup Guide

- src/pages/installing-spark/html-environment-setup.mdx
- src/pages/installing-spark/html-installation.mdx
Clearer indications on HTML tutorial.
- Javascript clarification
- Where to copy javascript spark imports
https://sparkdesignsystem.com/installing-spark/html-environment-setup
https://sparkdesignsystem.com/installing-spark/html-installation
> HTML Tutorial Clarification

- src/components/Footer.js
- src/pages/installing-spark/html-add-components.mdx
- src/pages/installing-spark/html-environment-setup.mdx
- src/pages/installing-spark/html-installation.mdx
> Add youtube videos to docs site and footer

- angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts
- angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
> bring singles back to double

- angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
- angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.stories.ts
- react/src/spark-exports-react.js
- src/pages/using-spark/components/button.mdx
Updates found through pre-release process.
> Release Updates

- html/settings/_settings.scss
Set Centered Column width to 64rem
> set centered column width to 64rem

- angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.stories.ts
- angular/projects/spark-angular/src/lib/spark-angular.module.ts
add sprkCenteredColumnModule to angular
update sprkText stories
> Pre release updates

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
> Alpha publish

- angular/package-lock.json
- angular/package.json
- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
update pkg json versions to final and npm audit fix
> update pkg json versions to final and npm audit fix

- src/pages/installing-spark/angular.mdx
> fix broken link

- angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
- html/components/_accordions.scss
- html/settings/_settings.scss
- react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
- react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.test.js
- src/data/sass-vars.json
Update accordion item trigger to be a button and add tests.
Fixes #2940 
expected.
> Update accordion item trigger to be a button and add tests

- html/components/award.stories.js
- Change `<a>` to `<button>`
- Tests are all in toggle
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2949
> HTML Award

- html/components/footer.stories.js
- src/data/sass-modifiers.json
- Change `<a>` to `<button>`
- Tests are all in toggle
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2949
> HTML Footer

- react/package-lock.json
- react/package.json
- react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.test.js
- react/src/components/toggle/SprkToggle.js
- react/src/components/toggle/SprkToggle.test.js
> update react toggle to button

- angular/package.json
- react/package.json
> lock up focus-visible

- react/src/components/footer/SprkFooter.stories.js
Update the structure of the Footer story in React to show that data being passed into the component. 
Fixes #2966
> Update React Footer Story

- html/utilities/_utilities.scss
- src/data/sass-modifiers.json
- src/data/sass-utilities.json
Remove bare button styles during attempt to make toggle a button
#2938 
> Remove bare button

- src/pages/using-spark/components/tabs.mdx
Removes incorrect information about Tabs activation and adds new information about supporting automatic activation.
Fixes #2967
> update Tabs documentation on site

- html/settings/_settings.scss
- src/data/sass-modifiers.json
- src/data/sass-vars.json
Update the center column width to 1232px.
Fixes #2958
> update center width column

- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.component.ts
Remove the striped class from `sprk-table`
Resolve console errors for `sprk-modal`
Release notes have been updated.
Fixes #3027 
Fixes #3028
> Angular Bugs - Table & Modal

- angular/package-lock.json
- angular/package.json
- html/package-lock.json
- html/package.json
- package-lock.json
- package.json
- react/package-lock.json
- react/package.json
> re-add sassdoc

- src/pages/installing-spark/installing-icons.mdx
Reviewed and updated the Icons documentation for the Installing Icons guide on the Gatsby site.
Fixes #3031
> update installing icons docs

- angular/projects/spark-angular/src/lib/components/inputs/Percentage.stories.ts
- src/data/sass-modifiers.json
Fix invalid % input story styles in sb.
Fixes #3024
> fix invalid % input story styles in sb angular

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
> add preventDefault for dropdown toggle

- html/settings/_colors.scss
- src/data/sass-modifiers.json
- src/data/sass-vars.json
- Change green and dark green to more accessible colors.
Fixes #3068 
expected.
> Change to a more accessible green

- angular/package-lock.json
- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
Adds a preventDefault() to the toggle click function in sprk-dropdown. This fixes a bug where the trigger reloaded the page on click.
> April 17th - hotfix publish

- angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
- html/base/_inputs.scss
- html/base/inputs/Checkbox.stories.js
- html/base/inputs/_checkbox.scss
- html/base/inputs/checkbox.js
- html/settings/_settings.scss
- html/spark-exports.js
- html/tests/checkbox.tests.js
- html/tests/generateIdForInput.tests.js
- html/utilities/generateIdForInput.js
- react/src/base/inputs/Checkbox.stories.js
- src/data/sass-modifiers.json
- src/data/sass-vars.json
- src/pages/using-spark/components/input.mdx
Style the Checkbox Input.
Add a utility function to do checks for the `for` and `id` on an input.
Add tests for checkbox.js
Add tests for generateIdForInput utility
Fixes #3063
> Checkboxes - HTML

- html/base/inputs/_checkbox.scss
- html/settings/_settings.scss
- react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.js
- react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.test.js
- src/data/sass-modifiers.json
- src/data/sass-vars.json
Updates the SprkSelectionInput to account for the new Checkbox and Radio classes.
Add tests.
Fixes #3093 
Fixes #3094
> Update Radio and Checkbox - React

- angular/projects/spark-angular/package-lock.json
- html/base/inputs/Checkbox.stories.js
- html/components/_toggle.scss
- html/settings/_settings.scss
- src/data/sass-modifiers.json
In going through the Publish PR these are updates to the code based on things I'm finding that we need to fix. Just hotfixes.
> updates to staging

- html/settings/_settings.scss
Update input border colors to darker gray for a11y reasons.
Fixes #3108 
expected.
> update input border colors to darker gray

- README.md
Update README from talking about Drizzle to now Gatsby/SB. The readme was out of date.
No issue. Not really needed.
> staging: Update README from talking about Drizzle to now Gatsby/SB

- README.md
Update README from talking about Drizzle to now Gatsby/SB.
No issue needed
> master: Update README from talking about Drizzle to now Gatsby/SB

- src/pages/installing-spark/angular.mdx
- src/pages/installing-spark/react.mdx
Add tutorial videos to Angular and React
Fixes #3135 #3134
> Add video embeds for react and angular

- .github/pull_request_template.md
> PR Template Update

- html/base/inputs/_radio.scss
- html/settings/_settings.scss
Update background color of disabled radio to match the rest of the inputs.
> update background color of disabled radio

- src/pages/installing-spark/angular.mdx
update install guide to include sprk javascript class.
> update install guide to include sprk javascript class

- html/components/stepper.stories.js
Fixes a11y issue with the ids not being unique.  The was a request from Olya.
No issue, fixing for the health of the system.
> make ids in steps unique

- .eslintrc
> turn off props-no-spreading rule

- html/settings/_settings.scss
- react/src/base/inputs/SprkCheckbox/SprkCheckboxGroup/SprkCheckboxGroup.js
- react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js
- react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.test.js
- react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js
- react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.test.js
- src/pages/using-spark/components/input.mdx
- Changes onChangeFunc to onChange for new Checklist and Radio in React
- adds missing `!default` in tooltip css
- granChildren typo
- missing `hasAngular` for huge checkbox
> Release Fixes

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
> Move position class logic from init to AferViewInit

- html/base/inputs/Checkbox.stories.js
- react/src/base/inputs/SprkCheckbox.stories.js
- react/src/base/inputs/SprkRadio.stories.js
Correct iframe sizes for checkboxes, and correct a typo
> Correct typo and iframes

- react/src/base/inputs/SprkCheckbox.stories.js
- react/src/base/inputs/SprkRadio.stories.js
Remove unnecessary aria-describedBy in checkbox/radio stories
> Remove unecessary aria-describedBy on stories

- src/pages/using-spark/components/input.mdx
Update urls to make iframes work.
> update input urls

- angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.ts
- react/src/objects/stack/SprkStack.js
- react/src/objects/stack/SprkStack.stories.js
- react/src/objects/stack/SprkStack.test.js
- react/src/objects/stack/components/SprkStackItem/SprkStackItem.js
- fix comment line lengths
- Adds 'analyticsString' to React Stack
- Remove empty default props from SprkStack and SprkStackItem
- Fix line lengths
Fixes #3299
> Stack upgrades

- angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
- angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.spec.ts
- angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.ts
- react/src/objects/centered-column/SprkCenteredColumn.js
- react/src/objects/centered-column/SprkCenteredColumn.test.js
Add analyticsString props and inputs to angular
Fixes #3309 
> Centered column: Update analytics string api

- angular/package.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
Updates the version number to account for staging changes so far, plus schematics feature.
Updates the build script to run the schematics script
> updates version, adds script to run schematics from build

- src/pages/using-spark/foundations/color.mdx
Update color contrast guideline WCAG version per Olya on the colors page.
> update color contrast guideline WCAG version per Olya

- src/pages/principles/accessibility-guidelines.mdx
Updates WCAG version per Olya.
> update to 2.1 per Olya

- .eslintrc
- angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts
- react/src/components/flag/SprkFlag.js
- react/src/components/flag/SprkFlag.test.js
- Change additionalMediaClasses to mediaAdditionalClasses
Change additionalBodyClasses to bodyAdditionalClasses
children is missing from propTypes.
- Update eslint rule that's conflicting with prettier
- https://github.com/prettier/eslint-config-prettier/issues/148
Fixes #3307 
> Flag: Update api, fix errors and formatting

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- src/pages/index.js
Update package numbers for version bump and update lodash versions.
Fixes #3332 
expected.
> update lodash and versions

- angular/projects/spark-angular/src/environment/environment.ts
> update angular env file

- angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.spec.ts
- angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.ts
- react/src/objects/box/SprkBox.js
- react/src/objects/box/SprkBox.stories.js
- react/src/objects/box/SprkBox.test.js
React - Fix lint errors
Angular - Add idString as an input and add test, fix lint errors
Fixes #3306
> Box Upgrades

- angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.ts
- react/src/components/icons/SprkIcon.js
- react/src/components/icons/SprkIcon.test.js
Update API for Angular and React Icons
Fixes #3313
> Update icon API

- angular/package-lock.json
- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
Update lodash to 4.17.20
Fixes #3349
> Update lodash to 4.17.20 for hotfix

- angular/projects/spark-angular/src/environment/environment.ts
> update ng env

- angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.directive.spec.ts
- angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.directive.ts
- react/src/base/typography/SprkHeading/SprkHeading.js
- react/src/base/typography/SprkHeading/SprkHeading.stories.js
- react/src/base/typography/SprkHeading/SprkHeading.test.js
React - Fix lint errors for SprkHeading
Angular - add the idString input and tests
Fixes #3311 
> Heading Upgrades

- react/src/components/awards/SprkAward.js
- react/src/components/awards/SprkAward.test.js
- react/src/components/buttons/SprkButton.js
- react/src/components/buttons/SprkButton.test.js
add propTypes.elementType to SprkAward & SprkButton
Fixes #3236 
expected.
> Update SprkButton & SprkAward propTypes

- src/pages/using-spark/components/icon.mdx
update icon sizes in docs page for icons to the new values based off style sheet settings.
Fixes #3379 
expected.
> update icon sizes in docs page for icons

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
Updates the version numbers for HTML and Angular for the publish.
> publish august 31, 2020

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
> bump versions for Color

- package-lock.json
- package.json
Updates the version of spark to the A version.
no issue
> update doc site to use alpha

- angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
Adds border to promo stories for consistency across frameworks
> Promo Updates

- storybook-utilities/icon-utilities/icon-loader.js
Update the storybook icon loader file name.
> update icon file name

- gatsby-config.js
> try spark assets url

- plugins/gatsby-symbol-set-fetch/gatsby-node.js
> use const instead of log

- gatsby-config.js
- plugins/gatsby-symbol-set-fetch/gatsby-node.js
> use spark assets

- angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts
- angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
- html/components/button.stories.js
- html/settings/_settings.scss
- react/src/components/buttons/SprkButton.js
- react/src/components/buttons/SprkButton.test.js
Updates the secondary button styles and spinners. Add tests for angular and react.
Fixes #3425 
expected.
> Button update

- angular/projects/spark-angular/src/environment/environment.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.ts
- html/components/highlight-board.stories.js
- react/src/components/highlight-board/SprkHighlightBoard.js
> update highlight board buttons to secondary per jason

- react/src/components/masthead/SprkMasthead.stories.js
- react/src/components/masthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js
Fixes #https://github.com/sparkdesignsystem/Backlog/issues/1265
expected.
> react masthead link style

- src/pages/using-spark/foundations/color-usage.mdx
Paragraph had a link that was an MDX. When it was converted into an HTML p tag, the link needed to turn into an anchor tag.
> Fix link that turned into HTML

- src/components/layouts/Layout.js
- src/scss/_spark-theme.scss
- add this banner
- tweaked the SkipNav css so they didn't conflict
> Upgrade Banner

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- html/package.json
- package-lock.json
- package.json
- react/package-lock.json
- react/package.json
> September 21 2020

- src/components/ComponentPreview.js
> v13 html deploy

- src/components/ComponentPreview.js
- src/components/DevDocLinks.js
> update sb links to v13 deploy

- src/pages/using-spark.mdx
> update using spark links to old sb links

- src/components/markdown-render/a.js
Converted the existing function to ES6 arrow function
Fixes #3479 
- [:white_check_mark: ] Build Component in HTML
- [:white_check_mark: ] Build Component in Angular
- [:white_check_mark: ] Build Component in React
- [:white_check_mark: ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
- [:white_check_mark: ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
- [:white_check_mark: ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)
- [:white_check_mark: ] Google Chrome
- [:white_check_mark: ] Google Chrome (Mobile)
- [:white_check_mark: ] Mozilla Firefox
- [:white_check_mark: ] Mozilla Firefox (Mobile)
- [ …
> converted to es6 arrow function

- package-lock.json
- src/components/layouts/UsingSparkLayout.js
Add missing prop types to `UsingSparkLayout.ts`
and eslint fixes as well.
Fixes #3478 
expected.
> feat: Add Prop Types

- src/components/CssUtilityTable.js
adds prop types to CssUtilityTable component
Fixes issue Number #3470 
expected.
> add proptypes package, and configure for component

- src/components/Header.js
Fixing Header.js prettier warnings.
#3514
> Fixing Header.js prettier warnings #3514

- src/components/Footer.js
fix spacing in Footer.js to meet prettier standards
Fixes #3512 
> fix spacing to meet prettier standards

- html/utilities/validation/isValidSSN.js
Converts isValidSSN function in html/utilities/validation folder
Issue Number 3508
> isValidSSN converted to an arrow function

- html/utilities/validation/setValidTextInput.js
Update setValidTextInput to be an arrow function
Fixes [#3510](https://github.com/sparkdesignsystem/spark-design-system/issues/3510)
expected.
> update setValidTextInput to be an arrow function

- src/components/layouts/HomepageLayout.js
Add missing proptypes and eslint fixes to HomepageLayout.js
Fixes #3471
> Added proptypes for the HomepageLayout

- src/components/InstallingSparkDocsMenu.js
Addressed Prettier warnings in `InstalllingSparkDocsMenu.js`
Fixes #3516 
- [ x ] Build Component in React
> Resolved all prettier warnings

- src/pages/index.js
makes  "Want to contribute" to black text #3492
Fixes #3492
> makes  "Want to contribute" to black text #3492

- html/utilities/validation/isValidDate.js
Updated  html/utilities/validation/isValiddate.js to be an arrow function
Fixes #3504 
expected.
> Updated isValiddate.js to be an arrow function

- html/utilities/toggleValue.js
This converts the toggleValue method to an arrow function
Fixes Issue #3503
> Convert toggleValue Fn to an arrow fn

- html/utilities/validation/setValidTick.js
Update setValidTick to be an arrow function
Fixes (#3511 )
> Update setValidTick to be an arrow function

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- html/package.json
- package-lock.json
- package.json
- react/package-lock.json
- react/package.json
- src/pages/principles/design-principles.mdx
> Update staging with changes from master

- angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
- Add additional Input for `variant` & set up deprecation for `alertType`
- Add typings for `alertType` & `variant` to restrict to success, fail, info.
- Add additional Input for `isDismissible` & set up deprecation for `dismissible`
- Add new inputs for iconName and dismissIconName 
- Add a boolean input of isVisible 
- Add an event emitter (@Ouput) to the alertDismiss() method.
- Update & add necessary tests
Fixes #3276 
Fixes #3524 
> Alert updates

- html/utilities/validation/setValidSelect.js
Updated setValidSelect to be an arrow function
Fixes #3509
> Update setValidSelect to be an arrow function

- angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.spec.ts
- angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.ts
- angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
- react/src/base/links/SprkLink.js
- react/src/base/links/SprkLink.stories.js
- react/src/base/links/SprkLink.test.js
React
- Add `isDisabled` prop.
- Add TODO: Comment
- Remove the variant option of base.
- Fix eslint errors
- Create Depreciation issue for future release - #1293
Angular
- Update the variant input option of icon to be hasIcon
- Create Depreciation issue for future release - #1293
Fixes #3429 
expected.
> Link Updates

- src/components/DevDocLinks.js
- src/pages/using-spark.mdx
- src/pages/using-spark/components/accordion.mdx
- src/pages/using-spark/components/alert.mdx
- src/pages/using-spark/components/award.mdx
- src/pages/using-spark/components/box.mdx
- src/pages/using-spark/components/button.mdx
- src/pages/using-spark/foundations/color-accessibility.mdx
- src/pages/using-spark/foundations/color-usage.mdx
- src/pages/using-spark/foundations/css-utilities.mdx
- src/pages/using-spark/foundations/sass-variables.mdx
- src/pages/using-spark/foundations/space.mdx
- src/pages/using-spark/foundations/typography.mdx
- src/scss/components/_blockquote.scss
Create clarity with our documentation
Affected pages:
> Doc clarity

- styles/tokens/toggle.json
> Toggle tokens

- html/components/_buttons.scss
- react/src/components/buttons/SprkButton.js
- react/src/components/buttons/SprkButton.stories.js
- react/src/components/buttons/SprkButton.test.js
- react/src/components/spinners/SprkSpinner.js
- react/src/components/spinners/SprkSpinner.test.js
Additional Context:
https://github.com/sparkdesignsystem/spark-design-system/issues/3569
Fixes #3317
Followup removal: https://github.com/sparkdesignsystem/spark-design-system/issues/3557
> React Button API Upgrades - separate Sprkpinner - Add isDisabled 

- styles/base/_typography.scss
> formatting extra line in type sass

- styles/tokens/masthead.json
> add new masthead token

- gatsby-config.js
> update icons link

- netlify.toml
- src/components/SassVarTable.js
- src/pages/installing-spark/angular.mdx
- src/pages/installing-spark/react.mdx
- src/pages/using-spark/foundations/design-tokens.mdx
> Design Tokens Documentation

- src/components/layouts/Layout.js
Update banner message on main branch
#3651
Zoom preview
Desktop preview
> update message banner on main

- styles/android/spark_design_tokens_strings.xml
- styles/tokens/input.json
Updates the margin of the selectionContainer
> update selectionContainer margin

- html/components/button.stories.js
* Added bullet point for `data-sprk-spinner-variant`
* Updated copy/paste code sample
> Update HTML Spinner Docs

- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- package.json
- react/package.json
- styles/package-lock.json
- styles/package.json
> Publish November 30th, 2020

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- react/package-lock.json
- react/package.json
> Publish nov 30 20

- html/components/autocomplete.stories.js
- src/pages/using-spark/components/autocomplete.mdx
Add invalid and disabled stories for all autocomplete.
- this is in progress
- in progress for other PR
> Add invalid and disabled stories for all autocomplete

- src/pages/using-spark/components/autocomplete.mdx
> Content update in gatsby

- html/tests/autocomplete.tests.js
> Autocomplete tests

- html/components/autocomplete.js
> dont select on elements directly

- html/components/autocomplete.stories.js
- Adds a View Source link to the Storybook docs
> HTML Autocomplete Beta Updates

- html/package-lock.json
> update html lock with styles 1.1.0

- react/package-lock.json
> add react lock with styles pkg

- angular/projects/spark-angular/package-lock.json
> angular lock with styles update

- react/src/base/inputs/Date.stories.js
- react/src/base/inputs/DatePicker.stories.js
- react/src/base/inputs/HelperText.stories.js
- react/src/base/inputs/Monetary.stories.js
- react/src/base/inputs/Password.stories.js
- react/src/base/inputs/Percentage.stories.js
- react/src/base/inputs/Phone.stories.js
- react/src/base/inputs/SSN.stories.js
- react/src/base/inputs/Search.stories.js
- react/src/base/inputs/Select.stories.js
- react/src/base/inputs/SprkLabel/SprkLabel.js
- react/src/base/inputs/SprkLabel/SprkLabel.test.js
- react/src/base/inputs/Text.stories.js
- react/src/base/inputs/Textarea.stories.js
> finish SprkLabel

- react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js
- react/src/base/inputs/SprkInput/SprkInput.js
- react/src/base/inputs/SprkInputContainer/SprkInputContainer.js
- react/src/base/inputs/SprkInputContainer/SprkInputContainer.test.js
- react/src/base/inputs/Text.stories.js
> add ariaDescribedBy to SprkInput, check for matching for/id

- react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js
- react/src/base/inputs/SprkRevealInput/SprkRevealInput.js
- react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.js
- react/src/base/inputs/SprkTextInput/SprkTextInput.js
- react/src/base/inputs/components/SprkInputIconCheck/SprkInputIconCheck.js
Add deprecation TODOs to:
SprkRevealInput
SprkTextInput
SprkSelectionInput
SprkErrorContainer
SprkInputIconCheck
> update deprecation todos

- react/src/base/inputs/SprkDatePickerInput/SprkDatePickerInput.js
- react/src/base/inputs/components/SprkInputLabel/SprkInputLabel.js
- react/src/base/inputs/components/SprkLabelLocationCheck/SprkLabelLocationCheck.js
Deprecation stories for:
SprkDatePickerInput
SprkInputLabel
SprkLabelLocationCheck
> Deprecation Messages

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.interfaces.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.interfaces.ts
> Masthead link

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
> add routerLink to sprk-dropdown

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
> alpha test changes for v11

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
revert sprk-dropdown to use sprk-link in necessary places
> dropdown updates

- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
> patch revert sprk link

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
> V11 branch

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
Patches v11 for sprk-masthead bug.
> Publish 11-patch, January 27, 2021

- react/src/base/inputs/Date.stories.js
- react/src/base/inputs/HelperText.stories.js
- react/src/base/inputs/Monetary.stories.js
- react/src/base/inputs/Password.stories.js
- react/src/base/inputs/Phone.stories.js
- react/src/base/inputs/SSN.stories.js
- react/src/base/inputs/Search.stories.js
- react/src/base/inputs/SprkInput/SprkInput.js
- react/src/base/inputs/SprkInput/SprkInput.test.js
- react/src/base/inputs/Text.stories.js
Remove width utli from SprkInput
> remove sprk-u-Width-100 class from SprkInput component

- react/src/base/inputs/SprkTextarea/SprkTextarea.js
- react/src/base/inputs/SprkTextarea/SprkTextarea.test.js
- react/src/base/inputs/Textarea.stories.js
- react/src/setup.test.js
- react/src/spark-exports-react.js
Adds new SprkTextarea component to Spark and associated tests with story files.
Fixes #3773 
**### Deploy Preview Reviewed and Approved - we are doing these audits at the end**
> Add new SprkTextarea component to Spark

- react/src/base/inputs/Date.stories.js
- react/src/base/inputs/DatePicker.stories.js
- react/src/base/inputs/HelperText.stories.js
- react/src/base/inputs/Monetary.stories.js
- react/src/base/inputs/Password.stories.js
- react/src/base/inputs/Percentage.stories.js
- react/src/base/inputs/Phone.stories.js
- react/src/base/inputs/SSN.stories.js
- react/src/base/inputs/Search.stories.js
- react/src/base/inputs/Select.stories.js
- react/src/base/inputs/SprkCheckbox.stories.js
- react/src/base/inputs/SprkFieldError/SprkFieldError.js
- react/src/base/inputs/SprkFieldError/SprkFieldError.test.js
- react/src/base/inputs/SprkRadio.stories.js
- react/src/base/inputs/Text.stories.js
- react/src/base/inputs/Textarea.stories.js
- react/src/spark-exports-react.js
Add new SprkFieldError component
Fixes #3761 
expected.
> React SprkFieldError

- react/src/base/inputs/Select.stories.js
- react/src/base/inputs/SprkInputContainer/SprkInputContainer.js
- react/src/base/inputs/SprkSelect/SprkSelect.js
- react/src/base/inputs/SprkSelect/SprkSelect.test.js
- react/src/spark-exports-react.js
> Add New React Select Input

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.interfaces.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
> add tests for link lengths and routerLink

- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.interfaces.ts
> add ngIfs for routerLink inputs

- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.interfaces.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.module.ts
> Promo && Highlight Board && Footer updates

- angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
> add dropdown tests

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
> update version for publish

- angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
> add router module to stories

- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.interfaces.ts
> add footer tests

- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
> masthead tests

- angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
> add tests for masthead

- react/src/base/inputs/SprkTextareaContainer/SprkTextareaContainer.js
- react/src/base/inputs/SprkTextareaContainer/SprkTextareaContainer.test.js
- react/src/base/inputs/Textarea.stories.js
- react/src/spark-exports-react.js
Adds the SprkTextareaContainer
Fixes #3772 
expected.
> add SprkTextareaContainer

- react/src/components/card/SprkCard.stories.js
- src/pages/index.js
> Homepage Cards - main

- storybook-utilities/storybook-theming/storybook-spark-theme.js
> Updates Storybook to use brand font

- src/pages/principles/accessibility-guidelines.mdx
> Content Update - Accessibility Guidelines

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
Upgrades lodash to latest in html and angular
> upgrade lodash

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/components/toggle.js
- html/package-lock.json
- html/package.json
- html/tests/toggle.tests.js
- react/package-lock.json
- react/package.json
- src/pages/principles/accessibility-guidelines.mdx
- storybook-utilities/storybook-theming/storybook-spark-theme.js
- styles/android/spark_design_tokens_strings.xml
- styles/components/_masthead.scss
- styles/package-lock.json
- styles/package.json
- styles/tokens/masthead.json
Update Staging with changes in main. This adds in everything that is in the main branch but was not in staging branch.
These changes have already been tested so for PR reviews, just make sure that the code looks good and everything that should be there is.
> Update Staging with changes in main

- styles/utilities/_utilities.scss
Need to add orange color utilities.
Related to #3887
> Add orange color utilities

- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
- html/components/modal.stories.js
- react/src/components/buttons/SprkButton.js
- react/src/components/modals/ModalFooter.js
- react/src/components/modals/SprkModal.js
- react/src/components/modals/SprkModal.stories.js
Moves the buttons of the modal to the right.
Moves the Confirm button to the right of the Cancel button.
Fixes #3927
> Update Modal Buttons

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.module.ts
- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
- html/components/dropdown.stories.js
- react/src/components/dropdown/SprkDropdown.js
- react/src/components/dropdown/SprkDropdown.stories.js
Update the Informational Dropdown to use the secondary button.
Fixes #3932
> Dropdown Secondary Button

- styles/android/spark_design_tokens_strings.xml
- styles/base/_links.scss
- styles/tokens/link.json
https://github.com/sparkdesignsystem/spark-design-system/pull/3946#discussion_r605194387
> Create has icon transition token (quick fix before staging goes into main)

- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- styles/package-lock.json
- styles/package.json
> add beta versions

- angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
- html/components/modal.stories.js
- react/src/components/modals/ModalFooter.js
> make modal buttons full width @xs

- styles/android/spark_design_tokens_strings.xml
- styles/base/inputs/_checkbox.scss
- styles/ios/SparkDesignTokens.swift
- styles/tokens/input.json
> update checkbox checked & focused styles

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
- styles/package-lock.json
- styles/package.json
> Publish 4 12 21

- angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
- react/src/components/dropdown/SprkDropdown.stories.js
Tiny changes to Angular and React stories to trigger a Netlify deploy
> trigger netlify

- src/components/layouts/Layout.js
Changes the text of the upgrade banner.
Previous Version:
This Version:
[Deploy Preview](https://60955037ea66420007a0f4e5--spark-design-system.netlify.app/)
> banner update

- react/src/base/inputs/SprkInput/SprkInput.js
- react/src/base/inputs/SprkInput/SprkInput.test.js
Update the SprkInput formatter to run once.
> update formatter to run once

- react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js
- react/src/base/inputs/SprkFieldError/SprkFieldError.js
- react/src/base/inputs/SprkFieldset/SprkFieldset.js
- react/src/base/inputs/SprkHelperText/SprkHelperText.js
- react/src/base/inputs/SprkInput/SprkInput.js
- react/src/base/inputs/SprkLabel/SprkLabel.js
- react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js
- react/src/base/inputs/SprkTextInput/SprkTextInput.js
- react/src/base/inputs/SprkTextarea/SprkTextarea.js
> React inputs

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/environment/environment.ts
> update angular pkg alpha version

- react/src/base/inputs/SprkCheckbox/SprkCheckboxGroup/SprkCheckboxGroup.js
- react/src/base/inputs/SprkCheckbox/SprkCheckboxGroup/SprkCheckboxGroup.test.js
- react/src/base/inputs/SprkInputContainer/SprkInputContainer.js
- react/src/base/inputs/SprkInputContainer/SprkInputContainer.test.js
- react/src/base/inputs/SprkRadio/SprkRadioGroup/SprkRadioGroup.js
- react/src/base/inputs/SprkRadio/SprkRadioGroup/SprkRadioGroup.test.js
- react/src/base/inputs/SprkTextareaContainer/SprkTextareaContainer.js
- react/src/base/inputs/SprkTextareaContainer/SprkTextareaContainer.test.js
> Additional checks for React Inputs

- react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js
- react/src/base/inputs/SprkDatePicker/SprkDatePicker.js
- react/src/base/inputs/SprkDatePicker/SprkDatePicker.test.js
- react/src/base/inputs/SprkFieldError/SprkFieldError.js
- react/src/base/inputs/SprkFieldset/SprkFieldset.js
- react/src/base/inputs/SprkHelperText/SprkHelperText.js
- react/src/base/inputs/SprkInput/SprkInput.js
- react/src/base/inputs/SprkInput/SprkInput.test.js
- react/src/base/inputs/SprkInputContainer/SprkInputContainer.test.js
- react/src/base/inputs/SprkLabel/SprkLabel.js
- react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js
- react/src/base/inputs/SprkSelect/SprkSelect.js
- react/src/base/inputs/SprkSelect/SprkSelect.test.js
- react/src/base/inputs/SprkTextarea/SprkTextarea.js
- react/src/base/inputs/SprkTextarea/SprkTextarea.test.js
- react/src/base/inputs/SprkTextareaContainer/SprkTextareaContainer.test.js
- react/src/utilities/helpers/isSprkInput/isSprkInput.test.js
> React input updates

- angular/projects/spark-angular/src/environment/environment.ts
- react/package-lock.json
- react/package.json
- react/src/utilities/formatters/sprkFormatDate.test.js
- react/src/utilities/formatters/sprkFormatMonetary.test.js
- react/src/utilities/formatters/sprkFormatPhone.test.js
- react/src/utilities/formatters/sprkFormatSSN.test.js
pre-release hotfix to add tests
> Update formatter tests to use new SprkInput

- react/src/base/inputs/SprkFieldError/SprkFieldError.js
- react/src/base/inputs/SprkFieldError/SprkFieldError.test.js
- react/src/base/inputs/SprkHelperText/SprkHelperText.js
- react/src/base/inputs/SprkHelperText/SprkHelperText.test.js
> update default ids

- react/src/base/inputs/SprkDatePicker/SprkDatePicker.js
- react/src/base/inputs/SprkInput/SprkInput.js
> add formatter check

- html/components/masthead.stories.js
No component changes, just added some clarification and linked kitchen-sink files.
> Add some clarifying documentation for masthead

- src/pages/using-spark/guides.mdx
- src/pages/using-spark/guides/content-style.mdx
Capitalization and quotation guides
2501768 [UX] Add to Doc Site: Content Style Guidelines: Capitalization and quotation
expected.
> Spark Content Style Guide

- styles/tokens/README.md
> Token Readme file

- angular/projects/spark-angular/package-lock.json
- html/package-lock.json
- react/package-lock.json
> update lock files

- angular/projects/spark-angular/package-lock.json
- html/package-lock.json
- react/package-lock.json
This reverts commit a223a31bb186e998da12eb1a4ce4665e35799a2a.
expected.
> Revert "update lock files"

- html/components/button.stories.js
- html/components/spinners.js
- html/package-lock.json
- html/package.json
- html/tests/spinners.tests.js
- Redo of the HTML spinner PR without the Tiny Date Picker changes.
- Sets HTML package.json and package-lock.json versions to `17.0.1`.
> Spinners Fix Without TDP Fix

- angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.stories.ts
- html/components/button.stories.js
- react/src/components/buttons/SprkButton.stories.js
Adds compact buttons (primary, secondary, and tertiary) to each storybook.
2416142
> Add compact buttons

- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- angular/projects/spark-angular/package.json
- angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
- angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
- angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
- gatsby-config.js
- html/components/dictionary.stories.js
- html/components/footer.stories.js
- html/components/icons.stories.js
- html/package.json
- package.json
- react/README.md
- react/package.json
- react/src/components/dictionary/SprkDictionary.stories.js
- react/src/components/dictionary/SprkDictionary.test.js
- react/src/components/footer/SprkFooter.stories.js
- react/src/components/icons/SprkIcon.stories.js
- src/components/Footer.js
- src/pages/installing-spark.mdx
- src/pages/using-spark.mdx
- src/pages/using-spark/foundations/design-tokens.mdx
- styles/package.json
> Rm updates

- angular/projects/spark-angular/src/lib/utilities/isElementVisible/isElementVisible.spec.ts
- angular/projects/spark-angular/src/lib/utilities/isElementVisible/isElementVisible.ts
Tested by looking at masthead, expanding mobile menu, and then making viewport large to see that it work well.
expected.
> Add window check for isElementVisible [angular]

- src/pages/using-spark/guides.mdx
- src/pages/using-spark/guides/alt-text.mdx
New Spark Guide: Alternative Text Guide
DZN 2531260
> added new alt text guide and updated guides page

- html/base/inputs/DatePicker.stories.js
- html/base/inputs/Search.stories.js
> add classes

- .github/CODEOWNERS
> remove me from CODEOWNERS

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
- styles/package-lock.json
- styles/package.json
> Publish - 8/30/21 (Staging Update)

- angular/projects/spark-angular/package-lock.json
- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
- styles/package-lock.json
> version bumps

- angular/projects/spark-angular/package.json
- html/package-lock.json
- html/package.json
- react/package-lock.json
- react/package.json
- styles/ios/SparkDesignTokens.swift
- styles/package-lock.json
- styles/package.json
- styles/tokens/button.json
> Publish 9 7 21

- src/components/layouts/Layout.js
> design changes
