src/patterns/fundamentals/typography/typekit.hbs
Today, it says "before the closing tag." That's not very specific. So, making some assumptions, I've provided a suggestion for editing that content.
=> Suggestion for content edit: clarify the placement for TypeKit

src/assets/drizzle/styles/components/_navigation.scss, src/patterns/components/inputs/collection.yaml
Fixes issue https://github.com/sparkdesignsystem/spark-design-system/issues/401
Inserts a pseudo-element at ```:target::before``` to offset the target from the top of the screen. This is to push the content down so it isn't hidden behind the navigation header.
Tested in all browsers. IE 11 doesn't support ```position: sticky;``` so the header scrolls off the screen, but it is respecting the new offset and pushing the jump targets down.
=> Sticky nav overlap

src/data/colors.yaml
Because that's correct––there's never just "purple" it's "purple medium"
=> Correct purple to purple medium

src/patterns/fundamentals/space/inset-short.hbs
- Updates `inset-tall` to `inset-short` spacing in the example as specified in #598
=> Fix Inset-short spacing in example

src/assets/drizzle/styles/components/_command.scss
- It updates the padding on the `drizzle-c-command` as it is currently too large
- Fixes #602
=> Fix the padding on the drizzle-c-command class

packages/spark-core/components/_alerts.scss, packages/spark-core/components/_icons.scss, packages/spark-core/package-lock.json, packages/spark-extras/package-lock.json, src/angular/projects/spark-core-angular/src/lib/components/sprk-alert/sprk-alert.component.ts, src/patterns/components/alerts/base.hbs
Have all the issues fixed by removing the SVG presentation attributes from the SVGs themselves. Only have 3 outstanding icons that I need to remove presentational code from so that they will take the stroke-width CSS overrides that we are doing. These three will require some time in sketch.
**Also to note: declaration in alerts for currentColor can be removed in future in favor of reusuable new CSS class for currentColor icons (that was added to HTML), but to avoid a breaking change, we keep the SCSS there for now**
=> fix up svg icon bugs

packages/spark-core/base/inputs/_error-container.scss
Right side is WITH this fix. The left side is the current state (without this fix).
This fixes issue https://github.com/sparkdesignsystem/spark-d
=> fix shrinking error icon with long error msgs

packages/spark-core/package.json
Closes [877](https://github.com/sparkdesignsystem/spark-design-system/issues/877)
=> chore(dependencies): bump dom-slider to 1.5.2

packages/spark-core/components/_masthead.scss, packages/spark-core/settings/_settings.scss, src/assets/drizzle/styles/utility/_toolkit-overrides.scss, src/patterns/components/masthead/collection.yaml, src/patterns/components/masthead/default.hbs, src/patterns/components/masthead/extended.hbs, src/patterns/utilities/single-property/height.hbs
=> masthead tweaks

packages/spark-core/package.json
I made this PR: https://github.com/BrentonCozby/dom-slider/pull/7 yesterday. The new version of dom-slider (1.5.3) fixes an issue with greedy monkey-patching of Node.prototype which is causing issues in JSDOM-based testing environments.
=> feat(package): bump dom-slider

packages/spark-core/settings/_settings.scss, src/patterns/components/dividers/collection.yaml
This updates the color, thickness, and docs for Dividers. I hard-coded the color because it is not a color we want used anywhere else due to accessibility concerns. No markup was changed. This PR closes #919
This is a completely superficial element. The color doesn't pass color contrast guidelines, but it doesn't need to.
=> Updating Divider color, thickness, and docs

packages/spark-core/base/inputs/_text-icon-input.scss, packages/spark-core/settings/_settings.scss, src/patterns/components/inputs/collection.yaml
This PR updates the positioning of the money input `$` so that no matter the length of the label the `$` does not get misplaced in the text box
Fixes #1083 
=> Money input $ gets misplaced when field label wraps to multiple lines

packages/spark-core/base/inputs/_selection-container.scss
Fixes a bug in Safari mobile where long checkbox labels causes the checkbox to shrink.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1104.
=> fix bug #1104

packages/spark-core/base/inputs/_selection-container.scss, src/angular/projects/spark-core-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
Adds a check to make sure the keydown event didn't happen while on the tab panel.
Still uses the Angular @HostListener so that event listening is setup and tore down appropriately. 
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/1131.
=> Fix bug #1131

src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts, src/patterns/components/masthead/angular/info/default.hbs
Closes the mobile navigation when router link navigation is complete.
Removes duplicate prop in Angular Docs
issue #1178 
issue #1182 
=> Fix bug #1178 & #1182

packages/spark-core/components/_buttons.scss, src/angular/projects/spark-extras-angular-highlight-board/src/lib/spark-extras-angular-highlight-board.component.ts, src/angular/src/app/spark-docs/masthead-docs/masthead-docs.component.ts, src/pages/tests/button.hbs, src/patterns/components/buttons/angular/code/at-small.hbs, src/patterns/components/buttons/at-small.hbs, src/patterns/components/buttons/collection.yaml, src/patterns/components/buttons/react/code/at-small.hbs, src/patterns/components/highlight-board/base.hbs, src/patterns/components/highlight-board/no-image.hbs, src/patterns/components/masthead/angular/code/default.hbs, src/patterns/components/masthead/default.hbs, src/react/projects/spark-core-react/src/SprkHighlightBoard/SprkHighlightBoard.js, src/react/projects/spark-core-react/src/SprkMasthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
Changed references from .sprk-c-Button--full\@sm and sprk-c-Button--full@sm to sprk-c-Button--full\@s and sprk-c-Button--full@s to keep naming consistency.
[1186](https://github.com/sparkdesignsystem/spark-design-system/issues/1186)
=> update sprk-c-Button--full@sm to be consistent naming

src/angular/src/app/spark-docs/input-docs/input-docs.component.ts, src/patterns/components/inputs/angular/code/monetary-disabled.hbs, src/patterns/components/inputs/angular/code/monetary-error.hbs, src/patterns/components/inputs/angular/code/monetary.hbs, src/patterns/components/inputs/collection.yaml
When we re-skinned and updated the inputs at the beginning of the year, we missed updating Angular’s monetary input.
It still has older classes from before the refactor so this PR updates them.
`sprk-b-TextInputIconContainer--monetary` -> `sprk-b-TextInputIconContainer--has-text-icon`
`sprk-b-TextInput--monetary` -> `sprk-b-TextInput--has-text-icon`
Fixes #1100
=> [Bug] Angular Inputs: Monetary Input doesnt show the $ icon

src/assets/drizzle/scripts/code-example-switch.js, src/templates/drizzle/code-example-switch.hbs
Shows the React code switch in staging. There's no harm in having this in staging and we need it for the demo. The nav doesn't have `?react` after every component and I'd rather not have us  add `?react` during the demo all the time.
Fixes #1164.
=> Show React code switch in staging

packages/spark-core/components/_masthead.scss, src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
**Problem:**
nav gets cut off when there are too many items on IE and FF
**Solution:**
- got rid of position:fixed on `.sprk-c-Masthead__narrow-nav`
- consolidate the angular's `__narrow-nav` `<nav>` with the ngIf `<div>` container
**Reasoning:**
- `.sprk-c-Masthead__narrow-nav` is currently `position: fixed`
- its parent (when open) is also `position: fixed`
- Nested fixed elements are redundant and unecessary, causing browsers like Firefox and IE to break layout padding and positioning.
- This change is safe to do because: `.sprk-c-Masthead__narrow-nav` is only visible when Masthead is in a `.sprk-c-Masthead--open` state.
- `.sprk-c-Masthead` starts as `position: sticky` but then replaced with `position: fixed` when `.sprk-c-Masthead--open` is applied
- With the first solution, …
=> [Bug] Narrow Nav scrolling in FF / Edge / IE11

src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-datepicker/sprk-datepicker.directive.ts, src/angular/projects/spark-core-angular/src/lib/spark-core-angular.module.ts, src/angular/src/app/spark-docs/stack-docs/stack-docs.component.ts
When angular is built in --prod, angular date picker input does not work. This is because it's not being packaged correctly with the flag.
Date picker uses a third party library called `tiny-date-picker`. There are a [two ways](https://nitayneeman.com/posts/how-to-add-third-party-library-in-angular-cli/) to bring in external libraries: **Injection**, and **import modules**.
In order to use injection, the library has to have typings, which `tiny-date-picker` does not have.
**Instead of creating one, we are opting to use the second method of importing it for the sake of simplicity.**
- There were concerns from @RCopeland that the import module method might an Angular anti-pattern.
- I couldn't find sources that say it is. Injection vs import is more of a choice based on situation, but …
=> [Bug] Angular Inputs: Date Picker Input Calendar does not appear on click

src/templates/drizzle/icon-gallery.hbs
There was an extra `&gt;` in `icon-gallery.hbs` that added an extra carat. This PR fixes all code samples for react icon
https://github.com/sparkdesignsystem/spark-design-system/issues/1253
=> [Bug] React icon non-working code samples

gulp/drizzle/config.js
copyable code blocks have extra spaces that break the code
jsx support is added to Beautifier which doesn't cause the extra spaces
Added a config that puts attributes into separated lines. Makes everything more readable and match closer to how we as front-end devs would implement a component. (Affects react, angular and vanilla)
#1243
=> [Doc] Fix Spark React code copy blocks in docs

packages/spark-card/_card.scss, src/patterns/components/card/collection.yaml
Adds a modifier to allow cards to be the full width of their container.
Fixes #1241
=> Allow cards to be full width - #1241

src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
Fix for removing the overflow class on angular mobile when completing navigation.
#1340
=> update navigation function

src/patterns/components/links/react/info/inline.hbs, src/patterns/components/masthead/react/info/default.hbs, src/react/projects/spark-react/src/SprkLink/SprkLink.js, src/react/projects/spark-react/src/SprkLink/SprkLink.test.js, src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.js, src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.test.js, src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Refactor SprkLink to accept {Link} as an element.
Updates Masthead in React and Angular to allow a user to provide a different href other than "/". Allows for internal and external links.
#1324
#1346 
=> Update SprkLink & Masthead for React

src/react/projects/spark-react/src/SprkAccordion/components/SprkAccordionItem/SprkAccordionItem.js, src/react/projects/spark-react/src/SprkDropdown/SprkDropdown.js, src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadSelector/SprkMastheadSelector.js, src/react/projects/spark-react/src/SprkToggle/SprkToggle.js
Updates SprkToggle, SprkAccordionItem and SprkDropdown to use preventDefault() in their onClick functions.
=> Update components using SprkLink

src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js, src/react/projects/spark-react/src/SprkPromo/SprkPromo.js
- Adds back default props to promo that were removed accidentally in the SprkLink PR.
- Fix masthead dropdown from rendering a blank header on big nav items. This was caused by removing the title defaultProp from MastheadDropdown.
https://github.com/sparkdesignsystem/spark-design-system/issues/1339t.
=> add back defaultProps to promo

src/angular/projects/spark-core-angular/package.json
Updates version after new 8.0.5 publish. I pulled down the new version from npm in an ng app and verified that it's working. Also, verified that the masthead fix is working.
=> Update version after new 8.0.5 publish

src/pages/docs/contributions.hbs, src/patterns/components/pagination/react/info/default.hbs, src/react/projects/spark-react/src/SprkPagination/SprkPagination.js, src/react/projects/spark-react/src/SprkPagination/SprkPagination.test.js
Updates SprkPagination Icons to be passed as props instead of hardcoded.
Fixes #1353
=> update SprkPagination icons

src/patterns/components/alerts/react/info/info.hbs, src/react/projects/spark-react/src/SprkAlert/SprkAlert.js, src/react/projects/spark-react/src/SprkAlert/SprkAlert.test.js, src/react/src/routes/SprkAlertDocs/SprkAlertDocs.js
Adds option to use custom icons in Alerts. Removes default props from alert.
https://github.com/sparkdesignsystem/spark-design-system/issues/1325.
=> Add option to use custom icons in Alerts

src/patterns/components/card/react/code/base.hbs, src/patterns/components/card/react/code/header.hbs, src/patterns/components/card/react/code/standout.hbs, src/patterns/components/card/react/code/teaser-variation.hbs, src/patterns/components/card/react/code/teaser.hbs, src/patterns/components/card/react/code/three-up.hbs, src/patterns/components/card/react/code/two-up.hbs, src/patterns/components/card/react/info/base.hbs, src/patterns/components/card/react/info/header.hbs, src/patterns/components/card/react/info/teaser.hbs, src/react/package.json, src/react/projects/spark-react/src/SprkCard/SprkCard.js, src/react/projects/spark-react/src/SprkCard/SprkCard.test.js, src/react/projects/spark-react/src/SprkCard/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.js, src/react/projects/spark-react/src/SprkCard/components/SprkCardTeaser/SprkCardTeaser.test.js, src/react/src/routes/SprkCardDocs/SprkCardDocs.js
- make a variant prop type
- update documentation for consistency
- bring markup that was originally outside of component inside
- Created an `additionalContentClasses` for configurability
- Remove empty default props--a standard agreed upon by the team
- Fixes and error
Fixes #1348
=> Card Improvements - React #1348

src/angular/projects/spark-core-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
Removes prevent.default() from the sprk-dropdown component to allow external links to work.
Fix #1364
=> Fix external links in sprk-dropdown - Angular

src/patterns/components/inputs/react/code/text-input-huge-disabled.hbs, src/patterns/components/inputs/react/code/text-input-huge-error.hbs, src/patterns/components/inputs/react/code/text-input-huge.hbs, src/patterns/components/inputs/react/global-info.hbs, src/patterns/components/inputs/text-input-huge-disabled.hbs, src/patterns/components/inputs/text-input-huge-error.hbs, src/patterns/components/inputs/text-input-huge.hbs, src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.js, src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.test.js, src/react/src/routes/SprkInputDocs/SprkTextInputDocs/SprkTextInputDocs.js
Create a react version of input text huge
Fixes #1227 
expected.
=> Create react text input huge

package.json, packages/spark/base/inputs/_labels.scss, packages/spark/base/inputs/_text-input.scss, packages/spark/settings/_settings.scss, src/angular/src/app/spark-docs/input-docs/input-docs.component.ts, src/patterns/components/inputs/angular/code/text-input-huge-disabled.hbs, src/patterns/components/inputs/angular/code/text-input-huge-error.hbs, src/patterns/components/inputs/angular/code/text-input-huge.hbs, src/patterns/components/inputs/collection.yaml, src/patterns/components/inputs/text-input-huge-disabled.hbs, src/patterns/components/inputs/text-input-huge-error.hbs, src/patterns/components/inputs/text-input-huge.hbs, src/patterns/components/inputs/text-input.hbs, src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.js, src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.test.js
Creates the angular huge input components // label is now invisible
fixes #1226 
=> Huge input angular // Update no label

packages/spark/components/_accordions.scss
Removes the margin: 0 auto; to no longer center the component on the page.
Fixes #1375
=> Remove accordion component centering

packages/spark/settings/_settings.scss, src/patterns/components/inputs/collection.yaml
Updates the $sprk-input-error-text-line-height line height from 1 to 1.4 to add spacing when the error message wraps to a second line.
Fixes #1394 
New line height - 1.4 per Ashley Morgan
=> Update Default Value of Inputs Error Line Height

src/patterns/components/masthead/react/code/default.hbs, src/patterns/components/masthead/react/code/extended.hbs, src/patterns/components/masthead/react/info/default.hbs, src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.js, src/react/src/routes/SprkMastheadDefaultDocs/SprkMastheadDefaultDocs.js, src/react/src/routes/SprkMastheadExtendedDocs/SprkMastheadExtendedDocs.js
Adds a spot in the react masthead to accommodate the new mobile navigation link.
Fixes #1461
=> Update Mobile Masthead - React

src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
Removes the sprk-u-Width-100 class to prevent character overflow issues.
Fixes #1061
=> Fix Overflow Issue in Navigation

src/assets/toolkit/styles/toolkit.scss
Overwrites the $sprk-masthead-translateY SASS variable to avoid animating the Masthead examples.
=> add masthead override for examples

src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.js, src/react/src/routes/SprkStepperDocs/SprkStepperDocs.js
Removing an extra `<p>` tag when the step doesn't have a description.
Fixes Issue https://github.com/sparkdesignsystem/spark-design-system/issues/1536
Before: 
After (slightly more compact):
=> Stepper - remove extraneous p tag

src/components/site-structure/Layout.js, src/pages/apidocumentation.js
Refactor Layout.js to use the presence of .stories. files instead of .mdx files to determine which links to draw.
=> converted structure to use allFile instead of mdx

src/angular/projects/spark-angular/src/public_api.ts
Explicitly export modules and components in the public_api.ts file. Prevents the angular compiler from aliasing the exports, allowing for individual import and use.
Fixes #1402
=> Update angular to allow individual module imports

packages/spark/settings/_settings.scss, src/angular/projects/spark-angular/src/public_api.ts
Add alias for typos that have been fixed and exports to avoid breaking changes.
Fixes #1692
=> Alias Typos and Component Exports

src/patterns/components/inputs/collection.yaml
Specifies where ```data-sprk-required-only``` goes.
- [x ] Update Spark Docs Vanilla
=> specify where the data-attr goes

src/patterns/components/masthead/collection.yaml, src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.js, src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.test.js, src/react/src/routes/SprkMastheadDefaultDocs/SprkMastheadDefaultDocs.js, src/react/src/routes/SprkMastheadExtendedDocs/SprkMastheadExtendedDocs.js
Enhances the scrolling functionality of the masthead in React. When the user scrolls down the page on a narrow viewport, the masthead animates off the page to create more space for content. When the user scrolls back up towards the top of the page, the masthead animates back in to give easy access to the navigation.
Fixes #1294
NOT TESTING REMOVAL OF EVENTLISTENERS ON UNMOUNT
- There is no functionality in JS to detect the presence of eventlisteners
- The only way is to use state or variables like attached = true/false
- Unable to detect state after component has been unmounted
- Testing unmount function is testing native functionality of react and is redundant
- The masthead is not "stuck" in IE and is …
=> React Masthead Enhanced Scrolling Functionality

packages/spark/base/monetaryInput.js, packages/spark/tests/monetaryInput.tests.js
Stops the monetary input from running the formatter when there is nothing in the input.
Fixes #1676 
=> testing if theres a value before running the formatter, add a test

src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts, src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts, src/patterns/components/masthead/collection.yaml
Enhances the scrolling functionality of the masthead in Angular. When the user scrolls down the page on a narrow viewport, the masthead animates off the page to create more space for content. When the user scrolls back up towards the top of the page, the masthead animates back in to give easy access to the navigation.
- Router event: Instead of using this router, make run this on every menu link instead
- `.sprk-c-Masthead--hidden` modifier: apply it only on breakpoints so we can reduce polling for resize events (more detail in comments of masthead scss)
Fixes #1640, Fixes #1768
- Skipping testing because the function inside of it is being tested already, and there's no need to test angular to see if it's …
=> Angular Masthead Enhanced Scrolling Functionality

src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.spec.ts, src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts, src/angular/src/app/spark-docs/input-docs/input-docs.component.ts, src/patterns/components/inputs/angular/code/select-huge-disabled.hbs, src/patterns/components/inputs/angular/code/select-huge-error.hbs, src/patterns/components/inputs/angular/code/select-huge.hbs, src/patterns/components/inputs/select-huge-disabled.hbs, src/patterns/components/inputs/select-huge-error.hbs, src/patterns/components/inputs/select-huge.hbs
Adds the ability to use the Huge Select input in Angular.
Fixes #1643 
=> Add Huge Select - Angular

src/angular/projects/spark-angular/package.json, src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts
Fixes #1774 
Supplies the $event to the onChange handler in sprkInput directive.
=> Angular --prod build bug fix

src/patterns/components/masthead/default.hbs
After speaking with @afebbraro, she confirmed that `$mobile-masthead-height` was a typo, and that the unit of measurement should be in pixels.
=> Clarifying documentation on masthead component.

packages/spark/base/inputs/_svg-icon-input.scss, src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts, src/angular/src/app/spark-docs/masthead-docs/masthead-docs.component.ts
Updates the monetary input css to not scroll on top of the masthead
Fixes #2089 
Before: 
After:
=> address z-index issue for monetary input

packages/spark/base/inputs/_select.scss
Adds in missing vendor prefixes to select.
Fixes #2098
- no docs needed
- none needed
- none needed
expected.
=> add missing vendor prefixes to select

packages/spark/_spark-angular.scss, src/angular/projects/spark-angular/src/environment/environment.ts, src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
move masthead styles to spark ng style file
no issue
expected.
=> move masthead styles to spark ng style file

src/angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.spec.ts, src/angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
Uses local state instead of vanilla js and a class to hide dismissed alerts.
=> uses visible state of alert instead of class to hide dismissed alerts

src/angular/projects/spark-angular/src/lib/components/sprk-stepper/sprk-stepper.component.ts
Removes the vanilla js usage from angular stepper
=> removes usage of vanilla js from stepper

src/angular/projects/spark-angular/src/lib/components/sprk-carousel/sprk-carousel.component.ts
removes vanilla js from angular carousel
=> removes usage of vanilla js from carousel

src/angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
removes vanilla js usage from angular tabbed nav
=> removes vanilla js usage from angular tabbed nav

spark/components/dividers/react/SprkDivider.stories.js, spark/components/dividers/vanilla/dividers.stories.js
- Improve titles of stories
- Add vanilla stories for dividers
Fixes #1797
=> Add vanilla divider storybook

spark/components/icons/vanilla/icons.stories.js, vanilla/.storybook/preview-body.html, vanilla/.storybook/preview-head.html
Loads icons into the Vanilla Storybook instance and adds the icon stories for vanilla.
Fixes #1803 
expected.
=> Icons - Vanilla

spark/components/pagination/react/SprkPagination.test.js
Make test selectors more specific so tests pass.  It is unclear why these tests started failing when we switched to Storybook.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2149
---
This line is returning different results depending on which site we run the tests in.
`expect(paginationItems.findWhere(x => x.text() === '...').length).toBe(2);`
Old Site - finds two nodes:
New Site - finds 4 nodes:
=> Fix React Pagination Unit Tests

spark/components/buttons/vanilla/button.stories.js
Make sure button renders in vanilla
Fixes #1795 
Netlify vanilla builds are not set up yet.
=> Add Vanilla Buttons to Story Book

spark/components/dropdown/vanilla/dropdown.stories.js
Adds the dropdowns to vanilla SB. While doing this, I may have found a bug in the dropdowns.js for vanilla and I logged it here: https://github.com/sparkdesignsystem/spark-design-system/issues/2158 - The bug was caught because in SB Vanilla, when you click on the dropdown trigger, it opens a new page. So dropdowns in SB Vanilla will do that until we discuss the bug #2158 and implement a preventDefault in there or we do something extra for vanilla SB.
Fixes #1799 
--- I didn't make any HTML changes to the component but in putting it into SB I noticed that the accessibility checks had 5 - 6 violations for this. I logged a bug so that we can look into this: …
=> Add dropdowns to vanilla SB

angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts, angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts, angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
Adds isSpinning to the sprk-button directive, when true, uses a ref to inject 
a sprk spinner into the element.
#2197
=> add spinning to sprk-button.directive

packages/spark/.npmignore
Update .npmignore files to keep test files out of the NPM bundle. In the spirit of https://gist.github.com/greim/e8e1bd3b1ed08a7505ce
=> Exclude test files from NPM packages

src/patterns/components/highlight-board/angular/code/no-image.hbs, src/patterns/components/highlight-board/angular/code/stacked.hbs, src/patterns/components/highlight-board/angular/info/default.hbs
Removed "subHeading" from the Angular docs for Highlight Board.
Fixes #1742 
=> remove subHeading from highlight board docs

react/src/base/links/SprkLink.js, react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js, react/src/components/masthead/SprkMasthead.js
We have been getting react test errors/warnings since the new docs site started. See below screenshot. I fixed this by researching and discovering a newer proptype that we should use going forward when we have a prop that can be of type react component. I left the old proptype values and added the new one. Leaving the old ones for now ensures that we don't have a breaking change. see: …https://github.com/facebook/prop-types/pull/211 for more info
Fixes #2238
This involves our react package and will be good to update that in the release notes when we launch that we added an additional proptype option of PropTypes.elementType to SprkLinks (element), SprkCardTeaser (ctaLinkElement, mediaLinkElement) and SprkMasthead (logoLinkElement). …
=> fix spark-react test errors by adding react component proptype

angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
Adds highlight board for sb
fixes duplicate imgSrc in card
Fixes #1872
=> Add highlight board components

react/src/base/inputs/SprkInput.stories.js, react/src/base/inputs/SprkTextInput/SprkTextInput.js, react/src/base/inputs/SprkTextInput/SprkTextInput.test.js, react/src/base/inputs/components/SprkInputElement/SprkInputElement.js, react/src/base/inputs/components/SprkTextareaCheck/SprkTextareaCheck.js
Adds logic to manage the hasValue state to add the necessary class when there is a default value provided in the Huge Text Input component - React
Discussion about whether this should happen in the SprkTextareaCheck or not occurred after Bob worked on this PR - 
https://github.com/sparkdesignsystem/spark-design-system/pull/2099
If I remember correctly, needs to be managed in SprkTextareaCheck because there is already a ref being passed by the SprkTextInput and couldn't create another one.
Fixes #2096
=> Fix Huge Text Input Default Value on IE/Edge - React

src/patterns/components/accordions/collection.yaml
Removes `$sprk-accordion-border-open` variable from the accordion docs
Fixes #2233 
=> removed sprk-accordion-border-open variable

html/objects/flag.stories.js
Adds the Flag object to HTML Storybook.
Fixes #2328
=> Flag - Storybook

html/components/centered-column.stories.js, storybook-theming/_docs.scss
Select placeholder elements by extra decorator class for layout placeholder styles This is better because the old method causes unexpected placeholder styles on any components that use the spark layout classes.
no issue, this is a follow up to the previous pr for adding the centered column layout
=> select placeholder elements by extra decorator class for layout placeholder styles

angular/.storybook/config.js, angular/projects/spark-angular/src/lib/components/inputs/sprk-input.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts, angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-list.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts, angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts, storybook-theming/_docs.scss
Tweak iframe heights in sb docs. This is in the angular SB. Also extended the max-width of the center column in the storybook docs pane.
no issue yet
=> tweak iframe heights in sb docs

html/components/_buttons.scss, html/components/_card.scss, html/components/_dictionary.scss, html/components/_dropdown.scss
Adds comments to the scss files for button, card, dictionary and dropdown.
Fixes #2414
=> Add sassdoc comments to button, card, dictionary and dropdown

html/components/dropdown.js, html/components/masthead.js
Adds preventDefault() to the dropdown trigger to prevent a click event navigating to another page.
Fixes #2441
=> Prevent Dropdown from navigating away - Vanilla

src/pages/using-spark/components/alert.mdx
Adds the Alert documentation to the Gatsby site.
Fixes #2272 
=> Add Alert docs to Gatsby site

src/pages/using-spark/components/footer.mdx
Adds footer docs to the Gatsby site.
Fixes #2277
=> Add Footer docs to NDS

angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts, html/components/accordion.stories.js, src/pages/using-spark/components/accordion.mdx
Adds Accordion docs to Gatsby site, Angular storybook and HTML storybook
Fixes #2273
=> Add Accordion docs to NDS

angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts, html/components/modal.stories.js, react/src/components/modals/SprkModal.stories.js, src/pages/using-spark/components/modal.mdx, storybook-utilities/markdownDocumentationLinkBuilder.js
Adds the Modal documentation to the Gatsby site and Storybook instances.
Fixes #2278
=> Modal docs

src/pages/using-spark/components/dropdown.mdx
Adds Dropdown documentation to the Gatsby site.
Fixes #2276
=> Add Dropdown docs to NDS

angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts, html/components/button.stories.js, react/src/components/buttons/SprkButton.stories.js, src/pages/using-spark/components/button.mdx
Adds Button documentation to the gatsby site and Storybook instances.
Fixes #2280
=> Add Button docs to NDS

angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts, html/base/link.stories.js, react/src/base/links/SprkLink.stories.js, src/pages/using-spark/components/link.mdx
Add Link documentation to Gatsby and Storybook instances.
Fixes #2279
=> Add Link docs to NDS

angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts, html/components/masthead.stories.js, react/src/components/masthead/SprkMasthead.stories.js, src/pages/using-spark/components/masthead.mdx
Adds the Masthead documentation to Gatsby and Storybook instances.
Fixes #2292
=> Add Masthead to NDS

html/objects/centered-column.stories.js, src/pages/using-spark/components/centered-column.mdx
Add centered column docs to gatsby.
Fixes #2327 
=> add centered column docs to gatsby

src/pages/using-spark/components/flag.mdx
Add flag docs to gatsby. When browser testing I noticed that the flag object in our HTML SB doesnt stack the image and text in small viewports. I made an issue here to fix it https://github.com/sparkdesignsystem/spark-design-system/issues/2517.
Fixes #2332 
=> add flag docs to gatsby

angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts, html/components/highlight-board.stories.js, react/src/components/highlight-board/SprkHighlightBoard.stories.js, src/pages/using-spark/components/highlight-board.mdx
Adds Highlight board docs to Gatsby site and Storybook instances.
Fixes #2284
=> Add Highlight Board docs to NDS

src/pages/using-spark/components/table.mdx
Adds Table documentation to the Gatsby site.
Fixes #2288
=> Add Table docs to NDS

angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts, html/components/pagination.stories.js, src/pages/using-spark/components/pagination.mdx
Adds Pagination docs to Gatsby site and Angular & HTML Storybook instances.
Fixes #2291
=> Add Pagination docs to NDS

src/pages/using-spark/components/toggle.mdx
Add Toggle documentation to the Gatsby site.
Fixes #2286
=> Add Toggle docs to NDS

html/components/stepper.stories.js, react/src/components/stepper/SprkStepper.stories.js, src/pages/using-spark/components/stepper.mdx
Adds Stepper documentation to Gatsby and React & HTML Storybook.
Fixes #2289
=> Add Stepper docs to NDS

angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts, html/components/tabs.stories.js, react/src/components/tabs/SprkTabs.stories.js, src/pages/using-spark/components/tabs.mdx
Adds Tabs documentation for Gatsby site and Storybook instances.
Fixes #2287
=> Add Tabs docs to NDS

src/pages/principles/accessibility-guidelines.mdx
Adds Accessibility Guidelines page to the Gatsby site.
Fixes #2206
=> add accessibility guidelines page to gatsby

src/components/PrinciplesDocsMenu.js, src/pages/principles/class-naming-convention.mdx
Adds the Class Naming Convention page under Principles on the Gatsby site.
Fixes #2208
=> Add Class Naming Convention Docs to NDS

react/src/components/modals/SprkModal.stories.js
Sets inlineStories to false in the Modal story file to fix Modal iframe height issue for react SB.
Fixes #2535 
expected.
Before:
After:
=> set inlineStories to false to fix Modal iframe height issue for react SB

src/pages/using-spark/foundations/space.mdx
Adds Spacing documentation to the Gatsby site.
Fixes #2302
=> add spacing docs to nds

html/base/typography.stories.js, src/pages/using-spark/foundations/typography.mdx
Adds Typography documentation to the Gatsby site and HTML Storybook instance.
Fixes #2304
=> Add Typography docs to NDS

src/components/ContextSubMenu.js, src/components/InstallingSparkDocsMenu.js, src/components/PrinciplesDocsMenu.js, src/scss/components/_menu.scss
Utilizes SprkLink, variant="simple" to update the styles of the side navigation on the Gatsby site.
Fixes #2594
=> update side nav links to be simple SprkLink

src/pages/installing-spark/installing-icons.mdx
Adds Installing Icons docs to Gatsby site.
Fixes #2367
=> add installing icons docs to gatsby

src/components/Footer.js
Adds footer copyright verbiage to the Gatsby site.
Fixes (#2308
=> update footer copyright on NDS

src/pages/using-spark/components/link.mdx
Change Base Link to "Default Link" for consistency
Make iframe of default link show up
Fixes #2596
=> Gatsby: Change to "Default Link"

html/objects/_box.scss, src/pages/using-spark/components/box.mdx
Adds the inset tall/short and misc space options to Box and updates the NDS box mdx page to document the new sizes.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2684
=> Add inset tall/short and misc space options to Box!

src/scss/components/_layout.scss
Fixes the homepage cards overlapping in ie11
=> setting flex-grow instead of flex, cause ie11

package.json, react/package-lock.json, react/package.json
Quick hotfix version bump to fix the issue where the stepper and stepperstep wasn't exported in spark-react-exports.js
=> patch spark-react package with spark exports fix

src/components/markdown-render/inlineCode.js
Change our inline code theme to github theme.
Upon Jane's reccomendation, the github theme matches our branding the closest, and I put in a issue to make a custom Spark Theme in the future.
=> Change inline code to Github prism theme

src/pages/installing-spark.mdx, src/pages/installing-spark/angular.mdx, src/pages/installing-spark/html-installation.mdx, src/pages/using-spark/components/input.mdx, src/scss/_spark-theme.scss
- convert long inline code to block code in Installation Guide
- "[BUG] (not a stopper) - weird horizontal scrolling iOS safari, this is because of the long code"
- "In the Angular guide, I think this should be "installing""
- "We call it "your-app" in one spot and "you-app" in another. This should be consistent."
- "This attribute is required..." is in here twice. Remove one."
- "[BUG] the "Getting Started Guides" link on https://spark-docs.netlify.com/installing-spark/, just reloads the current page"
- "should be a link to that section"
- update css for code in links [`like` this]()
=> NDS Cleanup

src/pages/principles/class-naming-convention.mdx
Because of the lone inline code snippet, it was causing horizontal scrolling on small viewports. 
Made it code blocks instead to fix.
=> Fix class naming convention snippets

angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts, angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
Add the ctaIcon input to sprk-card Angular. It adds the option to render an icon next to the CTA in the teaser variant, if the ctaType is a link and an icon name is provided. 
Adds tests for sprk-card to account for the additional input. 
Update the cardType and ctaType Inputs to explicitly check the types.
cardType checks for `base`, `teaser` && `teaserHeading` setting the default to `base`.
ctaType checks for `link` && `button` setting the default to `link`.
Fixes #1001
=> Adds ctaIcon input to sprk-card in Angular

react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.js, react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.test.js, src/pages/index.js, src/scss/_settings.scss, src/scss/components/_layout.scss, src/scss/objects/_color-swatch-grid.scss
- Adds support for the `onChange` function to be passed into input variants `checkbox` and `radio`.
- Updates the `select` and `hugeSelect` variants to use `onChange` while maintaining support for the `onChangeFunc` prop. Which will be deprecated in the future.
- Adds tests for the `onChange` props for `checkbox` and `radio` variants.
- Updates to the grids on the Gatsby doc site.
Fixes #2791 
=> Hotfix & Doc site grid updates

angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts
Angular awards component now has gaps between images.
Also fixed an found issue with the split classes not applying correctly.
Before:
After:
Fixes #1671
=> [BUG] Awards Component will display a gap between images - Angular 

html/components/_masthead.scss
Makes the Masthead logo clickable in IE 11.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2293
This is due to a bug in the IE 11 implementation of Flexbox, documented [here](https://github.com/philipwalton/flexbugs#flexbug-6). The default values for the `flex` shorthand have changed since IE 11's implementation, so we need to be explicit about the values we want to use.
expected.
Old clickable area:
New clickable area:
=> IE 11 Masthead Bug

angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts, html/components/_modals.scss, html/components/modal.stories.js, react/src/components/modals/SprkModal.js
This fix accounts for a [documented bug](https://github.com/philipwalton/flexbugs#flexbug-2) in IE 11's flexbox implementation.
- Creates a new CSS class `sprk-c-Modal__content` that is applied to the text container in the Wait variant story for Angular and HTML. (Applies only to Storybook Wait Modal examples, not the component itself).
- For React, adds the `sprk-c-Modal__content` class to the Modal component (This change applies to all usages of React Modals. No noticeable change to Storybook.).
- Fixes typo in HTML story
- Change Angular story to match lorem ipsum examples in React and HTML
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2193
Before:
After:
=> Fix Wait Modal display bug [IE 11] [3 Frameworks]

angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts, angular/projects/spark-angular/src/lib/directives/inputs/formatters/sprk-formatter-monetary/sprk-formatter-monetary.directive.spec.ts, angular/projects/spark-angular/src/lib/directives/inputs/formatters/sprk-formatter-monetary/sprk-formatter-monetary.directive.ts
- Added 3 new stories to Angular Storybook - Formatting, Validating, and Formatting and Validating
- removed that CSS class line because that class isn't used anywhere. Possibly a leftover from Huge Inputs?
- added the `dispatchEvent` section to re-trigger validation after the formatter adjusts the value.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2763
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2764
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2816
=> Angular Monetary Updates

angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
Fix broken github links in angular footer SB.
NO issue, this is a hotfix
=> Fix broken documentation links in Spark Angular Footer SB prop table

src/pages/installing-spark/html-installation.mdx
Before, this was wrong and didn't give users the best information.
After:
Fixes #2828
=> Update where to put data-sprk-main docs

angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts, html/base/inputs/Search.stories.js, react/src/base/inputs/Search.stories.js
Angular, React, HTML
Adding `type=search` to search inputs
Fixes #2824
=> Add type search to search inputs

angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.spec.ts, angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.spec.ts, angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.ts, angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.module.ts, angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.stories.ts, html/settings/_settings.scss, react/src/objects/centered-column/SprkCenteredColumn.js, react/src/objects/centered-column/SprkCenteredColumn.stories.js, react/src/objects/centered-column/SprkCenteredColumn.test.js, src/pages/using-spark/components/centered-column.mdx
- Adds Angular and React CenteredColumn components, tests, stories, and docs
- Changes the default max-width of the centered column from 64rem (1024px) to 77rem (1232px)
Fixes 2325
Fixes 2324
Fixes 2584
=> Centered Column

html/components/_spinners.scss, html/components/button.stories.js, html/settings/_settings.scss, src/data/sass-modifiers.json, src/data/sass-vars.json, src/pages/using-spark/components/button.mdx
=> Update Spinner Dark Color and Add Secondary Spinner Story to HTML

html/objects/_flag.scss, html/objects/flag.stories.js, src/pages/using-spark/components/flag.mdx
HTML - Refactor flag to use flexbox, and add reverse story
Fixes #2907
=> Refactor flag into flexbox, add reverse

react/src/components/buttons/SprkButton.js, react/src/components/buttons/SprkButton.stories.js, react/src/components/buttons/SprkButton.test.js, src/pages/using-spark/components/button.mdx
Add story for Loading Secondary.
Update SprkButton to pass `lightness` to SprkSpinner if `variant='secondary'`
Update documentation on Gatsby site.
Add unit test to cover passing `lightness` to SprkSpinner
Fixes #2913
=> Add Secondary Spinner to React

angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts, angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts, angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts, angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.spec.ts
Updates the button directive to add the spinner dark modifier class to secondary button spinners when they have a spinner. This also adds an input of idString, variant, and analyticsString. This new code also ensures that If sprkButtons are currently being used still with "class="sprk-c-Button--secondary" instead of using the new variant input they will not break. A unit test was added to check this. This also adds a new story to the Angular Storybook that showcases the secondary button with a spinner, "Loading Secondary".
Fixes #2912 
expected.
=> update spinner for secondary buttons in angular

angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts, angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.module.ts, angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.stories.ts, angular/projects/spark-angular/src/lib/spark-angular.module.ts, html/objects/_flag.scss, src/pages/using-spark/components/flag.mdx
Add sprk-flag component to Angular.
Add story file to Angular.
Add tests for sprk-flag.
Update Gatsby Documentation for sprk-flag.
Add sprk-flag to spark-angular.module.ts.
Fixes #2901
=> Add sprk-flag component to Angular

angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts, angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
- Adds a new story to the Angular Storybook for the deprecated Link Component.
- Adds a line to the Links documentation explaining the deprecation strategy.
- When the deprecated component is used in an application (including Storybook), it logs a warning.
Fixes 2920
=> Link Deprecation Docs and Warning

html/components/masthead.js, html/components/toggle.js, html/spark-exports.js, html/tests/generateAriaControls.tests.js, html/tests/masthead.tests.js, html/tests/toggleAriaExpanded.tests.js, html/utilities/generateAriaControls.js, html/utilities/toggleAriaExpanded.js
- adds `aria-controls` functionality to the mobile navigation menu in the HTML Spark Masthead
- adds `aria-expanded` functionality to the mobile navigation menu in the HTML Spark Masthead
- adds new HTML utility functions for `toggleAriaExpanded` and `generateAriaControls` with unit tests
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2957
=> HTML Masthead - add aria-controls and aria-expanded

html/components/toggle.js, html/package-lock.json, html/package.json, html/tests/toggle.tests.js, package-lock.json, react/src/components/buttons/SprkButton.js
- Upgrade `dom-slider` from version 1.9.3 to 2.1.0.
- Update API call in `toggle.js`
- Update unit tests
- This update fixes an issue in `dom-slider` that was causing collapsed toggle content to still be visible to screen readers.
- This is affecting:
- HTML Toggle
- HTML Accordion
- HTML Award
- HTML Footer
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2943
Before:
After:
=> dom-slider Upgrade

html/components/accordion.stories.js
- Change `<a>` to `<button>`
- remove `aria-controls` and `id` from the stories, as these will be autogenerated by `generateAriaControls`.
- CSS changes are all in other PRs. (https://github.com/sparkdesignsystem/spark-design-system/pull/2970)
- Tests are all in toggle
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/2946
=> HTML Accordion

angular/package-lock.json, angular/package.json, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts, html/components/_toggle.scss, html/components/masthead.js, html/components/toggle.js, html/components/toggle.stories.js, html/settings/_settings.scss, html/utilities/generateAriaControls.js, react/src/components/toggle/SprkToggle.js, src/data/sass-modifiers.json, src/data/sass-vars.json
Fixes #2944 
Tested all three frameworks in each browser since there were changes to all.
=> Update Angular, React and HTML Toggle components

angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts, react/src/components/toggle/SprkToggle.js, react/src/components/toggle/SprkToggle.test.js
Fixes #2948 
Coverage before:
Coverage after:
=> Add aria-controls to angular masthead narrow nav, update sprk-toggle, update SprkToggle

angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.module.ts, html/components/_masthead.scss, html/settings/_settings.scss, react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js, src/data/sass-modifiers.json, src/data/sass-vars.json
Update Masthead Accordion Item to be a button. 
Add `aria-expanded` to Masthead Accordion Item.
Remove unused `SprkLink` from the React Masthead Accordion Item.
Update SCSS and regenerate sassdoc jsons to match icon color in production.
Update and add tests for Masthead Accordion Item.
Fixes #3046
=> Update Masthead Accordion Item - Angular

html/components/masthead.stories.js
- In the HTML Masthead stories, change `<a>` to `<button>` for the masthead accordion summary examples.
- Remove `aria-controls` from these nodes so those values will be auto-generated by `toggle.js`
- Note: all behavior and tests for `aria-controls` and `aria-expanded` on the accordions are part of the HTML Toggle component, not the HTML Masthead.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/3045
=> HTML Masthead Accordion

html/base/inputs/_input-container.scss, html/settings/_settings.scss, html/utilities/_utilities.scss, src/components/Footer.js, src/data/sass-modifiers.json, src/data/sass-utilities.json, src/data/sass-vars.json
Update footer on site for new QL stuff.
Add new max-width: 100% utility
Add full width modifier to inputs
Fixes #2965 
Fixes #3019 
Input Modifier:
Utility:
=> Add max-width: 100% utility and inputs modifier

react/src/components/highlight-board/SprkHighlightBoard.js, react/src/components/highlight-board/SprkHighlightBoard.test.js, src/data/sass-modifiers.json, src/pages/using-spark/components/highlight-board.mdx
- Create a warning when a user has a sole secondary cta without a primary cta
- Do not render CTAs unless it has at least a primary cta
- Add tests
- Update design guidelines
Fixes #3079
=> Highlight Board cannot have a sole secondary cta

src/scss/_spark-theme.scss
Adds a background color to the gatsby site so when in dark mode you can still read our content.
Fixes #3088
=> Gatsby background

react/package-lock.json, react/package.json, react/src/base/links/SprkLink.js, react/src/base/links/SprkLink.test.js
Updates a faulty OR conditional in the React SprkLink component file that resulted in extra CSS classes being added to SprkLink components. Adds some extra expectations to jest teests
Fixes #3104 
=> React link hotfix

html/settings/_settings.scss
Reverts label font size based on request from design.
Fixes #3115 
expected.
=> revert label font size

html/base/inputs/_radio.scss
Adds focus and hover styles for selected radio buttons.
Fixes https://github.com/sparkdesignsystem/spark-design-system/issues/3118
=> Spark Radio - focus and hover style

angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts, html/components/masthead.stories.js, react/src/components/masthead/SprkMasthead.stories.js
Adds note about sticky masthead/IE11 to story files to let users know to except the masthead to not be sticky in IE11.
Fixes #3154 
=> add note about sticky masthead/IE11 to story files

src/pages/installing-spark/angular.mdx
Stepper and Tabs uses the class "sprk-u-HideWhenJs", which is dependent on if JS class is present. We used to have this step in our old docs but it got lost. Adding it back for now is a temp fix to get teams running until we decide to drop the hidewhenjs and use display--none instead OR we update angular pkg to add it automatically. 
Fixes https://github.com/sparkdesignsystem/Backlog/issues/1052
=> update angular install guide to include adding the sprk-u-JavaScript class

html/settings/_settings.scss
Removes two sass variables that were misspelled and are due for deprecation. 
Fixes #3233
=> remove old sass vars

react/src/base/inputs/SprkCheckbox.stories.js, react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js, react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.test.js, react/src/base/inputs/SprkLegend/SprkLegend.js, react/src/base/inputs/SprkLegend/SprkLegend.test.js, react/src/base/inputs/SprkRadio.stories.js, react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js, react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.test.js
Correct api to be more consistent with the direction we're going in 
from `disabled` to `isDisabled`
=> Correct api to isDisabled

html/components/tooltip.js, react/src/components/tooltip/SprkTooltip.js
Adds a 16px margin to the vertical edge of the tooltip that is furthest from the chevron at widths smaller than 328px.
Before:
After:
=> tooltip spacing at narrow layouts (HTML and React)

src/pages/installing-spark/react.mdx
Fixes a typo in the React Installation guide
=> Guide typo

angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts, angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
Spark dropdown in angular used to use the "value" to update the trigger text after a choice was clicked. This updates it to the text "title" of the choice as the text for the trigger text.
🛑BREAKING CHANGE: This is a breaking change because it changes the Trigger text from using the value on the choice object to the title text. This means that if someone has "Choice Value" set to the value and the "My Favorite Choice" set to the title. That now, the trigger text will show "My Favorite Choice" instead of "Choice Value"..
Fixes #3234 
=> Replace shown trigger text with the title rather than the value

angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.ts, angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts, angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts, react/src/components/dictionary/SprkDictionary.js, react/src/components/dictionary/SprkDictionary.test.js
**Angular Changes**
- Change `dictionaryType` to variant and add typings that show it can only be set to `striped`. Remove its default setting of `base`. It's not used for anything.
- Add new unit test for new variant Input.
- Add ability to add classes to the keys and values via Input
- Add new unit tests for additional classes for keys and values
- Add in `keyValuePairs` Input following deprecation strategy for `data` Input
- Make sure code comments for props say deprecation info
**React Changes**
- Add ability to add classes to the keys and values via prop
- Add tests for the new additional classes props for the keys and values
Fixes #3277
=> Dictionary Upgrades

angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.directive.spec.ts, angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.directive.ts, react/src/base/typography/SprkText/SprkText.js
- Fix eslint errors
- Remove `isPageTitle` from line 10. This is not used in this component. Must have been something someone copied over from the SprkHeading component.
- Add `idString`
Fixes #3312
=> Text Component Upgrades

angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.ts, angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts, react/src/components/tooltip/SprkTooltip.js, react/src/components/tooltip/SprkTooltip.stories.js, react/src/components/tooltip/SprkTooltip.test.js
- Fix eslint errors
- Provide a prop to accept a function that runs on toggle.
- Update `triggerIconType` to `triggerIconName`. The icon component will be updated to use name instead of type.
- Update `triggerIconType` to `triggerIconName`. The icon component will be updated to use name instead of type.
- refactor to not use ngOnInit
Fixes #3310
=> Tooltip Upgrades

html/components/_menu.scss, html/settings/_settings.scss
The icon for the masthead on mobile wasn't showing up. This is because we were removing the stroke and this is a custom icon. I added in that stroke and added new vars for the _menu.scss file. It's an older file and didn't have those settings.
Fixes #3380 
expected.
=> Add stroke width to menu icon and new vars

angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts, angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.ts, html/components/_dropdown.scss, html/components/dropdown.stories.js, html/settings/_settings.scss, react/src/components/dropdown/SprkDropdown.js, react/src/components/dropdown/SprkDropdown.stories.js
add new dd trigger class and make it black for all states and lightens the text highlight color.
working off a list
=> make dropdown trigger + icon black + use lightest purp for highlight

angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts, html/components/tooltip.stories.js
_Credit to Greeshma Mula of Rocket Technology for finding the bug that led to this PR. I am submitting this PR myself with her permission._
Updates the `button` element in the HTML tooltip example and Angular Spark tooltip implementation to include `type="button"`. This change will prevent a clicked tooltip from emitting the `submit` event. The most visible benefit of this fix is not causing unexpected things to happen if the clicked tooltip is within a form.
(The React component was not changed, as its button already includes the `type="button"` attribute and value.)
Fixes sparkdesignsystem/backlog#1178
[edit: Removed additional checklist items per Bob's suggestion]
=> Change HTML and Ng tooltip button types

package.json
fixes an issue where the gatsby clean cmd was in there twice due to a fetch/rebase/merge/update
=> remove rebase error

src/components/ContextSubMenu.js
adds prop types to ContextSubMenu component
Fixes Issue Number #3469
expected.
=> add proptypes to ContextSubMenu

src/components/layouts/PrinciplesLayout.js
This PR adds proptypes for the `PrinciplesLayout` to fix linter warnings.
Fixes #3477
=> Add proptypes for the PrinciplesLayout

html/utilities/validation/isValidPhone.js
isValidPhone converted into arrow function
isValidPhone function changed into an arrow function.
Fixes 3507
expected.
=> isValidPhone converted into arrow function

src/components/ContentWrapper.js
Added `propTypes` for `ContentWrapper`. Fixed eslint errors.
Fixes #3468 
Not sure if any of the checklist applies here.
=> Add propTypes for children prop in the ContentWrapper.js

src/components/ComponentPreview.js
Converted ComponentPreview into a functional component and removed constructor at `src/components/ComponentPreview.js`
Fixes #3502
=> Convert ComponentPreview.js into a functional component

src/components/layouts/InstallingSparkLayout.js
Adds proptypes and fixes eslint errors for `spark-design-system/src/components/layouts/InstallingSparkLayout.js`
https://github.com/sparkdesignsystem/spark-design-system/issues/3474
Removed checklist as it does not really apply.
=> Add  proptypes and fix eslint errors for InstallingSparkLayout.js

react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js, react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js, react/src/components/toggle/SprkToggle.js, react/src/components/toggle/SprkToggle.test.js
The default proptype uniqueID use at
- SprkToggle
- SprkMastheadAccordionItem
did not create unique IDs. Therefore now there's a check whether if prop with unique id is passed, and if not, a unique id is generated.
Relative tests were also updated.
Fixes #3472 
=> fix: Fix non-unique id on toggle and AccordionItem

src/components/Header.js
Updated masthead links to use `variant="simple"` instead of `variant="plain"` on the `<SprkLink>`'s.
Fixes #3491 
=> Top Navigation uses same link style as side Navigation

react/src/components/modals/SprkModal.js
Fixes the issue of the React modal not trapping the focus to elements inside of it. The issue was that the value for boolean checks for seeing if tab/escape keys are pressed or if the element is active was not being returned. Therefore, the part of the `SprkModal.js` code that sets the focus to the modal elements was never being hit.
Fixes #3531 
- [ x ] Build Component in React
- [ x ] Google Chrome
=> Fix focus for React modal component

react/src/components/dropdown/SprkDropdown.js, react/src/components/dropdown/SprkDropdown.test.js
Adds handling to select default choice in react dropdown, if isDefault: true is provided in option config.
Fixes #3530
expected.
=> feat: #3530 Add support for default choice in react dropdown

react/src/components/awards/SprkAward.js, react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.js, react/src/components/toggle/SprkToggle.js, react/src/components/toggle/SprkToggle.stories.js, react/src/components/toggle/SprkToggle.test.js
=> Toggle Updates - React

react/src/components/accordions/SprkAccordion.js, react/src/components/accordions/SprkAccordion.stories.js, react/src/components/accordions/SprkAccordion.test.js, react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js, react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.test.js
=> React Accordion Updates

react/src/components/awards/SprkAward.js, react/src/components/awards/SprkAward.stories.js, react/src/components/awards/SprkAward.test.js, react/src/objects/stack/SprkStack.js
- Award will no longer render an empty Toggle
- Award will no longer render with `sprk-o-CenteredColumn` by default. This class can be added back with `additionalClasses` if it is desired.
- Property `addClasses` is deprecated. Use `imageAdditionalClasses` instead.
- Property `linkAddClasses` is deprecated. Use `linkAdditionalClasses` instead.
- Remove the empty string default props
- Fix the eslint errors
- Add in oneOf for splitAt prop to define expected strings.
- Add in oneOf for itemSpacing prop to define the expected strings.
Fixes #3315
=> React Award API Updates

react/src/components/tabs/SprkTabs.js, react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.js, react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.test.js, react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.js, react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.test.js, react/src/components/toggle/SprkToggle.test.js
- Deprecate `tabBtnAddClasses` and replace with `tabBtnAdditionalClasses`.
- Deprecate `tabBtnAnalytics` and replace with `tabBtnAnalyticsString`.
- Deprecate `tabPanelAddClasses` and replace with `tabPanelAdditionalClasses`.ses
- remove empty default props (Main and in sub components)
Fixes #3297
=> React Tabs Updates

angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts, angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.ts, react/src/components/toggle/SprkToggle.test.js
- deprecate `title` and add `heading`
- deprecate `analyticsStringImgOne ` in favor of `imgOneAnalyticsString `
- deprecate `analyticsStringImgTwo ` in favor of `imgTwoAnalyticsString `
- deprecate `analyticsStringDisclaimer ` in favor of `disclaimerAnalyticsString `
- deprecate `additionalClassesImgOne ` in favor of `imgOneAdditionalClasses `
- deprecate `additionalClassesImgTwo ` in favor of `imgTwoAdditionalClasses `
- Add in string typings for the `splitAt` prop. (`tiny`,`small`, `medium`, `large` or `huge`.
- new Input `itemSpacing`
- move `data-id` from the `h2` inside the component to the outer container of component. This required adding a new `idString` Input to `sprk-stack`.
Fixes #3314
=> Angular Award API Updates

angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts, angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts, react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.js, react/src/components/toggle/SprkToggle.js, react/src/components/toggle/SprkToggle.test.js
https://github.com/sparkdesignsystem/Backlog/issues/1305
Fixes #3296
=> Toggle Updates - Angular

react/README.md
This PR adds a README to the react package.
It's updated to fit the react version copy of the root README, you can find the diff from the root readme [here](https://gist.github.com/Ahmeed2m/db22474bce104b1d1cfe7617053f5f4a/revisions?diff=split&short_path=b335630)
I have used the [docs](https://sparkdesignsystem.com/installing-spark/react) installation guide to make the needed changes.
Fixes #3465
=> Add a README to the React package

angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts, angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.component.ts, angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts, src/pages/using-spark/components/accordion.mdx
Fixes #3494
Issue to remove deprecated functionality: #3597 
Issue to make the component respond to changes to `isOpen`: #3568
=> Angular Accordion API Upgrades

angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
Adds analyticsString to Angular Modal Close button
Fixes #3452 
expected.
=> Add analyticsString to angular model close button

html/components/_masthead.scss, html/settings/_settings.scss
Updates the icon color for links in Masthead that are 'simple' links and have an icon.
Fixes #3576 
=> update icon color for simple links in masthead on hover

react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js, react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js, react/src/components/toggle/SprkToggle.js, react/src/components/toggle/SprkToggle.test.js
Updates the uniqueIds in SprkToggle and SprkMastheadAccordionItem to be unique if there are multiple on the same page, but not increment on toggle.
Fixes #3598 
Example of multiple toggles on the same page with different ids.
=> Fix uniqueIds from incrementing on toggle

styles/android/spark_design_tokens_colors.xml, styles/android/spark_design_tokens_strings.xml, styles/ios/SparkDesignTokens.swift, styles/tokens/link.json
Updates the link underline color to be purple instead of gray.
Fixes #3791
=> update link underline color

angular/projects/spark-angular/src/lib/components/inputs/Text.stories.ts
Update huge story text label to match react and angular sb examples.
Fixes #3719
=> fixes #3719 update angular huge story text label to match html/react

angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.component.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.interfaces.ts, angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.interfaces.ts
Adds outputs for dropdown/masthead selector being open/closed. Adds correct TS interface for the other sprk-dropdowns still left in masthead big-nav. Adds dropdown/masthead selector tests for choices with routerLink. Adds sprkText directives to the all paragraphs in dropdown/masthead selector, was previously added to some but not all. Adds routerLink ngIf test to selector. Fixes general typos in dropdown/masthead selector.
=> Add Dropdown Updates

react/src/components/card/SprkCard.stories.js, src/pages/index.js
- Changes the React Teaser Card story so that the CTA renders as an `a` element without `role="button"`.
- Change the 6 cards on the homepage in the same way.
This is so that the CTAs are identified as _links_, not _buttons_ for screen readers.
[More info on Screen Reader Link Navigation](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts#vo-mac-navigation)
Fixes #3857
=> Teaser Card CTA Element

angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.ts, angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts, html/components/card.stories.js, html/components/highlight-board.stories.js, react/src/components/card/SprkCard.stories.js, react/src/components/highlight-board/SprkHighlightBoard.js, react/src/components/highlight-board/SprkHighlightBoard.stories.js, react/src/components/highlight-board/SprkHighlightBoard.test.js
- Sets `alt=""` on the images in the Highlight Board stories. These images are presentational and should not be described to screen readers.
- Sets `alt="Learn more"` on the images in the Teaser Card stories. These images are links so they should always have alt 
text. In this case they should have text matching the CTA link, which is "Learn More". [When an image is the only content of a link, the text alternative for the image describes the unique function of the link.](https://www.w3.org/WAI/WCAG21/Techniques/html/H30)
- Removes the error message in React Highlight Board when imgAlt is not set.
Fixes #3850
=> Fix alt text for Highlight Board and Teaser Card

styles/android/spark_design_tokens_strings.xml, styles/components/_masthead.scss, styles/tokens/masthead.json
- These big navigational item links were the culprit.
- Some items have link type `--plain` and some have `--simple` which was bad
- On hover, these links have a red border bottom underline. Usually, these links have a transparent border bottom with the same size so things don't move around on hover
- `--plain` removes the border.
- There's a hover color change on its parent <li> (via `sprk-c-Masthead__link--big-nav`), but it didn't have that transparent border bottom default to prevent things from moving around.
- `sprk-c-Masthead__link--big-nav` now has a default transparent border so it takes up the same amount of space after hover/active etc.
- Resulting in a new style attribute, added to design tokens, and updated internal files. (no edited story files.
Fixes #3856 
If a checklist …
=> Fix extended masthead from pushing down content on hover

react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
Adds an additional function to handle updating the state of `ariaDescribedBy` in the SprkInputElement.
Fixes #3851
=> Fix no-set-state-on-update eslint error

src/pages/using-spark/guides/validation-messaging.mdx
- Olya noticed that we should specify that we're following Level AA accessibility guidelines. Add that detail to the disclaimer at the bottom.
- Also fixed the image to have a limited width on larger viewports.
**This is changing just a few words**
=> Quickfix: WCAG messaging on validation guide

src/pages/index.js
Fixes console error for undefined prop value on spark doc site.
=> Remove unecessary secondary variant on SprkLink

styles/ios/SparkDesignTokens.swift, styles/tokens/link.json
=> Remove bolding on hover on links on dark backgrounds

react/src/base/inputs/SprkRevealInput/SprkRevealInput.js
Adds a new `disabled` prop to `SprkRevealInput` that is passed on to the input, the checkbox, and the Show Password label. This is not a breaking change because `disabled` was already being used in the story and passed to the input through `...rest`.
=> React Disabled Password bug

angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.ts, angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts, angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.ts, angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
- Adds the `ariaHidden` Input to `sprk-icon`.
- Adds a unit test to cover the new behavior.
- Updates Alert, Card, and Tooltip to use the new Input.
Fixes 2453085
=> Angular Icon aria-hidden

angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-content/sprk-card-content.directive.ts, angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-header/sprk-card-header.directive.ts, angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-media/sprk-card-media.directive.ts, angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-content/sprk-promo-content.directive.ts, angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-heading/sprk-promo-heading.directive.ts, angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-media/sprk-promo-media.directive.ts, angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-subheading/sprk-promo-subheading.directive.ts, angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.ts, angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.directive.ts, angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.ts, angular/projects/spark-angular/src/lib/directives/sprk-divider/sprk-divider.directive.ts
In Angular 10 (and TypeScript 3) `@HostBinding('class.example') true;` was interpreted such that `true` was the value and thus the HostBinding was applied properly. In Angular 11 (and TypeScript 4), `true` is instead interpreted as the property name, with no value, meaning a falsey value, and the HostBinding does not get applied. This change, backwards compatible with all previous versions, should fix these issues in newer versions of Angular and TypeScript.
n/a
=> Add property names to host bindings

angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts, react/src/components/masthead/SprkMasthead.stories.js, styles/android/spark_design_tokens_dimens.xml, styles/ios/SparkDesignTokens.swift, styles/tokens/masthead.json
Before:
- Bottom padding is 16px and it made it look uneven
- It's also not vertically centered within the masthead
After:
- Bottom padding is now matching the top, which is 8px
Misc:
- Removed unnecessary box class around masthead storybook
- Remove unecessary right padding on compact button so all packages match
- 
Fixes 2465094
- no documentation change
- No changes in accessibility
expected.
=> Masthead logo area - Make top and bottom padding match 8px [ALL PACKAGES]

angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts, react/src/components/tooltip/SprkTooltip.js, react/src/components/tooltip/SprkTooltip.test.js
Add a containerAdditionalClasses input for tooltip
**2515338**
No changes in how it renders on browsers.
expected.
=> Add a containerAdditionalClasses input for tooltip

angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
Reverts how we're importing lodash in sprk-masthead. This is to fix a build error in kitchen-sink.
=> Revert Lodash Import

angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.component.ts
Adds subscription logic so click events are reset if result items are dynamically added or removed.
```javascript
this.resultItems.changes.subscribe((_) => {
this.bindClickEvents();
});
```
Currently `sprk-autocomplete` sets up the click event on each of its child result items in `ngAfterContentInit`. Autocomplete results are often dynamically added/removed/changed at runtime (due to filtering). When items are dynamically added/removed, their click events were not being correctly set up, since `ngAfterContentInit` doesn't run when those items are changed.
=> Autocomplete Click Fix

angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio.stories.ts, html/base/inputs/Radio.stories.js, package-lock.json, react/src/base/inputs/SprkRadio.stories.js
Updates to the Radio Group headers to make their text and style consistent across storybooks. Additionally, text for each Radio item updated for consistency as well.
2275405
=> Radio headers

html/components/button.stories.js, html/components/spinners.js, html/package-lock.json, html/package.json, html/tests/spinners.tests.js
Adds a new data attribute to the HTML Spinner API that allows submit buttons to skip the `disabled` behavior.
=> HTML Spinner Hotfix

react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js, react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.test.js
Updates the `SprkAccordionItem` component so that there are no more console errors when passing the props `isDefaultOpen` or `isOpen`.
Fixes 2518810
=> React Accordion Console Error Fix

react/src/components/dropdown/SprkDropdown.js
Remove `isDefault` from being passed through the spread operator and resolving the console error. 
Fixes 2527686
=> Resolve Dropdown console error

angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.spec.ts, angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
Adds the `additionalClasses` input on `sprk-modal` in Angular.
Fixes 2397868
=> Add additionalClasses input for Angular Modal

angular/projects/spark-angular/package.json
Doesn't change how package is built, just changes the pkg.json to remove the warning. Works in angular 11 on local. I tested the current spark package in my starter repo app that i upgraded to angular 11 in the browsers on my local mac. 
Fixes (Issue Number that this PR is closing out) - not sure if there is an issue
=> update angular 11 pkg json version

src/pages/using-spark/foundations/typography.mdx
Fixes this "Display Two" jump link on the Typography page.
Preview: https://deploy-preview-4042--spark-design-system.netlify.app/using-spark/foundations/typography#headers
=> Fix broken typography link

styles/android/spark_design_tokens_strings.xml, styles/base/inputs/_select.scss, styles/tokens/input.json
Updates the icon position for selects so that it isn't masked by the autofill.
Fixes 2546822
=> update icon position in select

angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts, angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.component.ts
Adds aria roles to the `ul` and `li` of an Angular Accordion so the accessibility checks pass.
2670578
=> added aria roles to ul and li

react/src/components/footer/SprkFooter.stories.js, styles/android/spark_design_tokens_strings.xml, styles/tokens/link.json
This PR fixes the footer inline link bug that appears on the visited state. The underline color was transparent on visited and should now be white. Changed the tokens style values for visited-border-bottom. Should apply to all frameworks.
2689258
=> Footer inline link fix
